/**
 * Generated by `createschema meter.MeterResource 'name:Text;'`
 * In most cases you should not change it by hands
 * Please, don't remove `AUTOGENERATE MARKER`s
 */

const dayjs = require('dayjs')
const { faker } = require('@faker-js/faker')
const { get } = require('lodash')

const { generateGQLTestUtils, throwIfError } = require('@open-condo/codegen/generate.test.utils')

const { MeterResource: MeterResourceGQL } = require('@condo/domains/meter/gql')
const { MeterReadingSource: MeterReadingSourceGQL } = require('@condo/domains/meter/gql')
const { Meter: MeterGQL } = require('@condo/domains/meter/gql')
const { MeterReading: MeterReadingGQL } = require('@condo/domains/meter/gql')
const { MeterReadingFilterTemplate: MeterReadingFilterTemplateGQL } = require('@condo/domains/meter/gql')
const { DEFAULT_ORGANIZATION_TIMEZONE } = require('@condo/domains/organization/constants/common')
const { FLAT_UNIT_TYPE } = require('@condo/domains/property/constants/common')
const { DELETE_METER_AND_METER_READINGS_MUTATION } = require('@condo/domains/meter/gql')
const { PropertyMeter: PropertyMeterGQL } = require('@condo/domains/meter/gql')
const { PropertyMeterReading: PropertyMeterReadingGQL } = require('@condo/domains/meter/gql')
const { MeterReportingPeriod: MeterReportingPeriodGQL } = require('@condo/domains/meter/gql')
const { MeterResourceOwner: MeterResourceOwnerGQL } = require('@condo/domains/meter/gql')
const { EXPORT_PROPERTY_METER_READINGS_QUERY } = require('@condo/domains/meter/gql')
const { INTERNAL_DELETE_METER_READINGS_MUTATION } = require('@condo/domains/meter/gql')
const { REGISTER_METERS_READINGS_MUTATION } = require('@condo/domains/meter/gql')
const { MeterReadingsImportTask: MeterReadingsImportTaskGQL } = require('@condo/domains/meter/gql')
const { MeterReadingExportTask: MeterReadingExportTaskGQL } = require('@condo/domains/meter/gql')
const { REGISTER_PROPERTY_METERS_READINGS_MUTATION } = require('@condo/domains/meter/gql')
const { MeterUserSetting: MeterUserSettingGQL } = require('@condo/domains/meter/gql')
/* AUTOGENERATE MARKER <IMPORT> */

const MeterResource = generateGQLTestUtils(MeterResourceGQL)
const MeterReadingSource = generateGQLTestUtils(MeterReadingSourceGQL)
const Meter = generateGQLTestUtils(MeterGQL)
const MeterReading = generateGQLTestUtils(MeterReadingGQL)
const MeterReadingFilterTemplate = generateGQLTestUtils(MeterReadingFilterTemplateGQL)
const PropertyMeter = generateGQLTestUtils(PropertyMeterGQL)
const PropertyMeterReading = generateGQLTestUtils(PropertyMeterReadingGQL)
const MeterReportingPeriod = generateGQLTestUtils(MeterReportingPeriodGQL)
const MeterResourceOwner = generateGQLTestUtils(MeterResourceOwnerGQL)
const MeterReadingsImportTask = generateGQLTestUtils(MeterReadingsImportTaskGQL)
const MeterReadingExportTask = generateGQLTestUtils(MeterReadingExportTaskGQL)
const MeterUserSetting = generateGQLTestUtils(MeterUserSettingGQL)
/* AUTOGENERATE MARKER <CONST> */

const { COLD_WATER_METER_RESOURCE_ID } = require('@condo/domains/meter/constants/constants')
const { makeClientWithServiceConsumer } = require('@condo/domains/resident/utils/testSchema')
const { makeLoggedInAdminClient } = require('@open-condo/keystone/test.utils')
const { EXCEL } = require('@condo/domains/common/constants/export')
const {
    makeContextWithOrganizationAndIntegrationAsAdmin,
    createTestBillingProperty,
    createTestBillingAccount
} = require("@condo/domains/billing/utils/testSchema")
const { makeClientWithResidentUser } = require("@condo/domains/user/utils/testSchema")
const { createTestProperty } = require("@condo/domains/property/utils/testSchema")
const { createTestResident, createTestServiceConsumer } = require("@condo/domains/resident/utils/testSchema")


async function createTestMeterResource (client, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        ...extraAttrs,
    }
    const obj = await MeterResource.create(client, attrs)
    return [obj, attrs]
}

async function updateTestMeterResource (client, id, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    if (!id) throw new Error('no id')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        ...extraAttrs,
    }
    const obj = await MeterResource.update(client, id, attrs)
    return [obj, attrs]
}

async function createTestMeterReadingSource (client, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        ...extraAttrs,
    }
    const obj = await MeterReadingSource.create(client, attrs)
    return [obj, attrs]
}

async function updateTestMeterReadingSource (client, id, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    if (!id) throw new Error('no id')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        ...extraAttrs,
    }
    const obj = await MeterReadingSource.update(client, id, attrs)
    return [obj, attrs]
}

async function makeClientWithResidentAndMeter (extraMeterAttrs = {}) {
    const client = await makeClientWithServiceConsumer()
    const adminClient = await makeLoggedInAdminClient()
    const { property, organization, serviceConsumer, resident } = client
    const [resource] = await MeterResource.getAll(client)
    client.resource = resource
    const [meter, attrs] = await createTestMeter(adminClient, organization, property, resource, {
        accountNumber: serviceConsumer.accountNumber,
        unitName: resident.unitName,
        ...extraMeterAttrs,
    })
    client.meterAttrs = attrs
    client.meter = meter
    return client
}


async function createTestMeter (client, organization, property, resource, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    if (!organization || !organization.id) throw new Error('no organization.id')
    if (!property || !property.id) throw new Error('no property.id')
    if (!resource || !resource.id) throw new Error('no resource.id')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }
    const accountNumber = faker.random.alphaNumeric(8)

    const attrs = {
        dv: 1,
        sender,
        number: faker.random.alphaNumeric(5),
        unitName: faker.random.alphaNumeric(5),
        unitType: FLAT_UNIT_TYPE,
        organization: { connect: { id: organization.id } },
        property: { connect: { id: property.id } },
        resource: { connect: { id: resource.id } },
        accountNumber,
        numberOfTariffs: 1,
        ...extraAttrs,
    }
    const obj = await Meter.create(client, attrs)
    return [obj, attrs]
}

async function createTestMeters (client, createAttrs = []) {
    if (!client) throw new Error('no client')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const defaultValues = {
        number: () => faker.random.alphaNumeric(5),
        unitName: () => faker.random.alphaNumeric(5),
        unitType: () => FLAT_UNIT_TYPE,
        accountNumber: () => faker.random.alphaNumeric(8),
        numberOfTariffs: () => 1,
    }

    const attrs = createAttrs.map(original => {
        const data = { ...original }
        for (const key in defaultValues) {
            if (!(key in data)) {
                data[key] = defaultValues[key]()
            }
        }
        return {
            data: { ...data, dv: 1, sender }
        }
    })

    return Meter.createMany(client, attrs)
}

async function updateTestMeter (client, id, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    if (!id) throw new Error('no id')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        ...extraAttrs,
    }
    const obj = await Meter.update(client, id, attrs)
    return [obj, attrs]
}

async function updateTestMeters (client, updateAttrs = []) {
    if (!client) throw new Error('no client')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = updateAttrs.map(updateData => {
        const { id, data } = updateData
        return { id, data: { ...data, dv: 1, sender } }
    })

    return Meter.updateMany(client, attrs)
}

async function createTestMeterReading (client, meter, source, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    if (!meter || !meter.id) throw new Error('no meter.id')
    if (!source || !source.id) throw new Error('no source.id')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        meter: { connect: { id: meter.id } },
        source: { connect: { id: source.id } },
        date: faker.date.recent(),
        value1: String(faker.datatype.number()),
        ...extraAttrs,
    }
    const obj = await MeterReading.create(client, attrs)
    return [obj, attrs]
}

async function updateTestMeterReading (client, id, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    if (!id) throw new Error('no id')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        ...extraAttrs,
    }
    const obj = await MeterReading.update(client, id, attrs)
    return [obj, attrs]
}

async function createTestMeterReadingFilterTemplate (client, employee, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    if (!employee || !employee.id) throw new Error('no employee.id')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }
    const name = faker.random.alphaNumeric(5)
    const ticketUnitFilter = [faker.random.alphaNumeric(5)]
    const fields = { unitName: ticketUnitFilter }

    const attrs = {
        dv: 1,
        sender,
        employee: { connect: { id: employee.id } },
        name,
        fields,
        ...extraAttrs,
    }

    const obj = await MeterReadingFilterTemplate.create(client, attrs)
    return [obj, attrs]
}

async function updateTestMeterReadingFilterTemplate (client, id, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    if (!id) throw new Error('no id')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        ...extraAttrs,
    }
    const obj = await MeterReadingFilterTemplate.update(client, id, attrs)
    return [obj, attrs]
}


async function _internalDeleteMeterAndMeterReadingsByTestClient (client, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        ...extraAttrs,
    }
    const { data, errors } = await client.mutate(DELETE_METER_AND_METER_READINGS_MUTATION, { data: attrs })
    throwIfError(data, errors)
    return [data.result, attrs]
}
async function createTestPropertyMeter (client, organization, property, resource, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    if (!organization || !organization.id) throw new Error('no organization.id')
    if (!property || !property.id) throw new Error('no property.id')
    if (!resource || !resource.id) throw new Error('no resource.id')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        numberOfTariffs: 1,
        number: faker.random.alphaNumeric(5),
        organization: { connect: { id: organization.id } },
        property: { connect: { id: property.id } },
        resource: { connect: { id: resource.id } },
        ...extraAttrs,
    }
    const obj = await PropertyMeter.create(client, attrs)
    return [obj, attrs]
}

async function createTestPropertyMeters (client, createAttrs = []) {
    if (!client) throw new Error('no client')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const defaultValues = {
        number: () => faker.random.alphaNumeric(5),
        numberOfTariffs: () => 1,
    }

    const attrs = createAttrs.map(original => {
        const data = { ...original }
        for (const key in defaultValues) {
            if (!(key in data)) {
                data[key] = defaultValues[key]()
            }
        }
        return {
            data: { ...data, dv: 1, sender }
        }
    })

    return PropertyMeter.createMany(client, attrs)
}

async function updateTestPropertyMeter (client, id, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    if (!id) throw new Error('no id')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        ...extraAttrs,
    }
    const obj = await PropertyMeter.update(client, id, attrs)
    return [obj, attrs]
}

async function updateTestPropertyMeters (client, updateAttrs = []) {
    if (!client) throw new Error('no client')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = updateAttrs.map(updateData => {
        const { id, data } = updateData
        return { id, data: { ...data, dv: 1, sender } }
    })

    return PropertyMeter.updateMany(client, attrs)
}

async function createTestPropertyMeterReading (client, meter, source, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    if (!meter || !meter.id) throw new Error('no meter.id')
    if (!source || !source.id) throw new Error('no source.id')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        date: faker.date.recent(),
        value1: String(faker.datatype.number()),
        meter: { connect: { id: meter.id } },
        source: { connect: { id: source.id } },
        ...extraAttrs,
    }
    const obj = await PropertyMeterReading.create(client, attrs)
    return [obj, attrs]
}

async function updateTestPropertyMeterReading (client, id, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    if (!id) throw new Error('no id')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        ...extraAttrs,
    }
    const obj = await PropertyMeterReading.update(client, id, attrs)
    return [obj, attrs]
}

async function createTestMeterReportingPeriod (client, organization, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    if (!organization.id) throw new Error('organization.id')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        organization: { connect: { id: organization.id } },
        ...extraAttrs,
    }
    const obj = await MeterReportingPeriod.create(client, attrs)
    return [obj, attrs]
}

async function updateTestMeterReportingPeriod (client, id, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    if (!id) throw new Error('no id')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        ...extraAttrs,
    }
    const obj = await MeterReportingPeriod.update(client, id, attrs)
    return [obj, attrs]
}

async function createTestMeterResourceOwner (client, organization, resource, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    if (!organization || !organization.id) throw new Error('no organization.id')
    if (!resource || !resource.id) throw new Error('no resource.id')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        organization: { connect: { id: organization.id } },
        resource: { connect: { id: resource.id } },
        ...extraAttrs,
    }
    const obj = await MeterResourceOwner.create(client, attrs)
    return [obj, attrs]
}

async function updateTestMeterResourceOwner (client, id, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    if (!id) throw new Error('no id')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        ...extraAttrs,
    }
    const obj = await MeterResourceOwner.update(client, id, attrs)
    return [obj, attrs]
}


async function _internalDeleteMeterReadingsByTestClient (client, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        ...extraAttrs,
    }
    const { data, errors } = await client.mutate(INTERNAL_DELETE_METER_READINGS_MUTATION, { data: attrs })
    throwIfError(data, errors)
    return [data.result, attrs]
}

async function exportPropertyMeterReadingsByTestClient (client, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        timeZone: DEFAULT_ORGANIZATION_TIMEZONE,
        ...extraAttrs,
    }
    const { data, errors } = await client.query(EXPORT_PROPERTY_METER_READINGS_QUERY, { data: attrs })
    throwIfError(data, errors)
    return [data.result, attrs]
}

/**
 * @param {Pick<Property, 'address'>} property
 * @param {boolean} isPropertyMeters
 * @param {Partial<RegisterMetersReadingsReadingInput>} extraAttrs
 * @return {RegisterMetersReadingsReadingInput}
 */
const createTestReadingData = (property, extraAttrs = {}, isPropertyMeters = false) => ({
    address: property.address,
    addressInfo: {
        ...!isPropertyMeters ? { unitType: FLAT_UNIT_TYPE } : {},
        ...!isPropertyMeters ? { unitName: get(property, ['map', 'sections', 0, 'floors', 0, 'units', 0, 'label'], faker.random.alphaNumeric(4)) } : {},
        globalId: get(property, ['addressMeta', 'data', 'house_fias_id'], faker.datatype.uuid()),
    },
    ...!isPropertyMeters ? { accountNumber: faker.random.alphaNumeric(12) } : {},
    meterNumber: faker.random.numeric(8),
    meterResource: { id: COLD_WATER_METER_RESOURCE_ID },
    date: dayjs().toISOString(),
    value1: faker.random.numeric(3),
    value2: faker.random.numeric(4),
    meterMeta: {
        numberOfTariffs: 2,
    },
    ...extraAttrs,
})

async function registerMetersReadingsByTestClient(client, organization, readings, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    if (!organization || !organization.id) throw new Error('no organization.id')
    if (!readings) throw new Error('no readings')
    if (!Array.isArray(readings)) throw new Error('readings is not an array')

    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        organization: { id: organization.id },
        readings,
        ...extraAttrs,
    }
    const { data, errors } = await client.mutate(REGISTER_METERS_READINGS_MUTATION, { data: attrs })
    throwIfError(data, errors)
    return [data.result, attrs]
}

async function createTestMeterReadingsImportTask (client, user, organization, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    if (!user || !user.id) throw new Error('no user.id')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        user: { connect: { id: user.id } },
        organization: { connect: { id: organization.id } },
        ...extraAttrs,
    }
    const obj = await MeterReadingsImportTask.create(client, attrs)
    return [obj, attrs]
}

async function updateTestMeterReadingsImportTask (client, id, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    if (!id) throw new Error('no id')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        ...extraAttrs,
    }
    const obj = await MeterReadingsImportTask.update(client, id, attrs)
    return [obj, attrs]
}

async function createTestMeterReadingExportTask (client, user, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    if (!user || !user.id) throw new Error('no user.id')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        format: EXCEL,
        where: {},
        sortBy: ['createdAt_DESC'],
        user: { connect: { id: user.id } },
        ...extraAttrs,
    }
    const obj = await MeterReadingExportTask.create(client, attrs)
    return [obj, attrs]
}

async function updateTestMeterReadingExportTask (client, id, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    if (!id) throw new Error('no id')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        ...extraAttrs,
    }
    const obj = await MeterReadingExportTask.update(client, id, attrs)
    return [obj, attrs]
}

async function createTestMeterUserSetting (client, user, meter, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    if (!user || !user.id) throw new Error('no user.id')
    if (!meter || !meter.id) throw new Error('no meter.id')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        user: { connect: { id: user.id } },
        meter: { connect: { id: meter.id } },
        name: faker.random.alpha(8),
        ...extraAttrs,
    }
    const obj = await MeterUserSetting.create(client, attrs)
    return [obj, attrs]
}

async function updateTestMeterUserSetting (client, id, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    if (!id) throw new Error('no id')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        ...extraAttrs,
    }
    const obj = await MeterUserSetting.update(client, id, attrs)
    return [obj, attrs]
}

async function makeResidentWithOwnMeter (admin) {
    const unitName = faker.random.alphaNumeric(8)
    const { context, organization } = await makeContextWithOrganizationAndIntegrationAsAdmin()
    const residentClient = await makeClientWithResidentUser();
    const [property] = await createTestProperty(admin, organization)
    const [resource] = await MeterResource.getAll(admin, { id: COLD_WATER_METER_RESOURCE_ID })
    const [billingProperty] = await createTestBillingProperty(admin, context)
    const [billingAccount] = await createTestBillingAccount(admin, context, billingProperty)
    const [resident] = await createTestResident(admin, residentClient.user, property, {
        unitName,
    })
    await createTestServiceConsumer(admin, resident, organization, {
        accountNumber: billingAccount.number,
    })

    const [meter] = await createTestMeter(admin, organization, property, resource, {
        accountNumber: billingAccount.number,
        unitName,
    })

    return {
        residentClient,
        meter,
    }
}

async function registerPropertyMetersReadingsByTestClient (client, organization, readings, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    if (!organization || !organization.id) throw new Error('no organization.id')
    if (!readings) throw new Error('no readings')
    if (!Array.isArray(readings)) throw new Error('readings is not an array')

    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        organization: { id: organization.id },
        readings,
        ...extraAttrs,
    }
    const { data, errors } = await client.mutate(REGISTER_PROPERTY_METERS_READINGS_MUTATION, { data: attrs })
    throwIfError(data, errors)
    return [data.result, attrs]
}
/* AUTOGENERATE MARKER <FACTORY> */

module.exports = {
    MeterResource, createTestMeterResource, updateTestMeterResource,
    MeterReadingSource, createTestMeterReadingSource, updateTestMeterReadingSource,
    Meter, createTestMeter, updateTestMeter, createTestMeters, updateTestMeters,
    MeterReading, createTestMeterReading, updateTestMeterReading,
    MeterReadingFilterTemplate, createTestMeterReadingFilterTemplate, updateTestMeterReadingFilterTemplate,
    makeClientWithResidentAndMeter,
    _internalDeleteMeterAndMeterReadingsByTestClient,
    PropertyMeter, createTestPropertyMeter, updateTestPropertyMeter, createTestPropertyMeters, updateTestPropertyMeters,
    PropertyMeterReading, createTestPropertyMeterReading, updateTestPropertyMeterReading,
    MeterReportingPeriod, createTestMeterReportingPeriod, updateTestMeterReportingPeriod,
    MeterResourceOwner, createTestMeterResourceOwner, updateTestMeterResourceOwner,
    _internalDeleteMeterReadingsByTestClient,
    exportPropertyMeterReadingsByTestClient,
    createTestReadingData, registerMetersReadingsByTestClient,
    MeterReadingsImportTask, createTestMeterReadingsImportTask, updateTestMeterReadingsImportTask,
    MeterReadingExportTask, createTestMeterReadingExportTask, updateTestMeterReadingExportTask,
    MeterUserSetting, createTestMeterUserSetting, updateTestMeterUserSetting, makeResidentWithOwnMeter,
    registerPropertyMetersReadingsByTestClient,
/* AUTOGENERATE MARKER <EXPORTS> */
}
