// Each string will be passed to the chain of plugins
const BULK_SEARCH_STRATEGY_EACH_ITEM_TO_PLUGINS = 'EACH_ITEM_TO_PLUGINS'

// All strings will be passed to first plugin, then strings without result will be passed to the 2nd plugin
const BULK_SEARCH_STRATEGY_ALL_ITEMS_TO_EACH_PLUGIN = 'ALL_ITEMS_TO_EACH_PLUGIN'

const BULK_SEARCH_STRATEGIES = [
    BULK_SEARCH_STRATEGY_EACH_ITEM_TO_PLUGINS,
    BULK_SEARCH_STRATEGY_ALL_ITEMS_TO_EACH_PLUGIN,
]

const SEARCH_ERROR_COMMON = 'SEARCH_ERROR_COMMON'
const SEARCH_ERROR_NO_PLUGINS = 'SEARCH_ERROR_NO_PLUGINS'
const SEARCH_ERROR_NOT_FOUND = 'SEARCH_ERROR_NOT_FOUND'

const BULK_SEARCH_CHUNK_SIZE = 5

module.exports = {
    BULK_SEARCH_STRATEGY_EACH_ITEM_TO_PLUGINS,
    BULK_SEARCH_STRATEGY_ALL_ITEMS_TO_EACH_PLUGIN,
    BULK_SEARCH_STRATEGIES,
    SEARCH_ERROR_COMMON,
    SEARCH_ERROR_NO_PLUGINS,
    SEARCH_ERROR_NOT_FOUND,
    BULK_SEARCH_CHUNK_SIZE,
}
