/**
 * Generated by `createservice property.CheckPropertyWithAddressExistService --type queries`
 */
async function canCheckPropertyWithAddressExist() {
    // TODO(dkoviazin): more complex access check for mobile devices
    return true
}

/*
  Rules are logical functions that used for list access, and may return a boolean (meaning
  all or no items are available) or a set of filters that limit the available items.
*/
module.exports = {
    canCheckPropertyWithAddressExist,
}
