/**
 * Generated by `createservice news.GetNewsItemsRecipientsCountersService --type mutations`
 */
const { filter, pick, uniq, uniqBy } = require('lodash')

const { GQLCustomSchema, allItemsQueryByChunks } = require('@open-condo/keystone/schema')

const access = require('@condo/domains/news/access/GetNewsItemsRecipientsCountersService')
const {
    countUniqueUnitsFromResidents,
    getUnitsFromProperty,
} = require('@condo/domains/news/utils/serverSchema/recipientsCounterUtils')


const CHUNK_SIZE = 50

const GetNewsItemsRecipientsCountersService = new GQLCustomSchema('GetNewsItemsRecipientsCountersService', {
    types: [
        {
            access: true,
            type: 'input GetNewsItemsRecipientsCountersInput { dv: Int!, sender: JSON!, organization: OrganizationWhereUniqueInput!, newsItemScopes: [NewsItemScopeWhereInput!]! }',
        },
        {
            access: true,
            type: 'type GetNewsItemsRecipientsCountersOutput { propertiesCount: Int!, unitsCount: Int!, receiversCount: Int! }',
        },
    ],

    queries: [
        {
            access: access.canGetNewsItemsRecipientsCounters,
            schema: 'getNewsItemsRecipientsCounters(data: GetNewsItemsRecipientsCountersInput!): GetNewsItemsRecipientsCountersOutput',
            resolver: async (parent, args) => {
                const { data: { newsItemScopes, organization: { id: organizationId } } } = args

                const isAllOrganization = filter(newsItemScopes, {
                    property: null,
                    unitType: null,
                    unitName: null,
                }).length > 0

                let propertiesCount = 0, unitsCount = 0, receiversCount

                const unitsByProperty = {}

                if (isAllOrganization) {
                    await allItemsQueryByChunks({
                        schemaName: 'Property',
                        chunkSize: CHUNK_SIZE,
                        where: { organization: { id: organizationId }, deletedAt: null },
                        /**
                         * @param {Property[]} chunk
                         * @returns {Property[]}
                         */
                        chunkProcessor: (chunk) => {
                            propertiesCount += chunk.length
                            for (const property of chunk) {
                                unitsCount += (property.unitsCount + property.uninhabitedUnitsCount)

                                if (!unitsByProperty[property.id]) {
                                    unitsByProperty[property.id] = []
                                }

                                unitsByProperty[property.id] = [...unitsByProperty[property.id], ...getUnitsFromProperty(property).map(u => u.unitName)]
                            }

                            return []
                        },
                    })
                    receiversCount = await countUniqueUnitsFromResidents(unitsByProperty)
                } else {
                    const propertiesIds = uniq(newsItemScopes.map(({ property: { id } }) => id))
                    propertiesCount = propertiesIds.length

                    const unitsByProperty = {}

                    /**
                     * @type {Object<string, {unitType: string?, unitName: string?}[]>}
                     */
                    const scopesUnitsByProperties = newsItemScopes.reduce((acc, scope) => {
                        return {
                            ...acc,
                            [scope.property.id]: uniqBy([
                                ...(acc[scope.property.id] || []),
                                pick(scope, ['unitName', 'unitType']),
                            ]),
                        }
                    }, {})

                    await allItemsQueryByChunks({
                        schemaName: 'Property',
                        chunkSize: CHUNK_SIZE,
                        where: { id_in: propertiesIds, deletedAt: null },
                        /**
                         * @param {Property[]} chunk
                         * @returns {Property[]}
                         */
                        chunkProcessor: (chunk) => {
                            for (const property of chunk) {
                                const propertyUnitsFromScope = scopesUnitsByProperties[property.id]
                                const isAllProperty = filter(propertyUnitsFromScope, {
                                    unitType: null,
                                    unitName: null,
                                }).length > 0

                                if (!unitsByProperty[property.id]) {
                                    unitsByProperty[property.id] = []
                                }

                                if (isAllProperty) {
                                    unitsCount += (property.unitsCount + property.uninhabitedUnitsCount)
                                    unitsByProperty[property.id] = [...unitsByProperty[property.id], ...getUnitsFromProperty(property).map(u => u.unitName)]
                                } else {
                                    const unitsFromProperty = getUnitsFromProperty(property)
                                    for (const unitFilter of propertyUnitsFromScope) {
                                        if (unitFilter.unitName) {
                                            const filteredUnits = filter(unitsFromProperty, unitFilter)
                                            unitsCount += filteredUnits.length
                                            unitsByProperty[property.id] = [...unitsByProperty[property.id], ...filteredUnits.map(u => u.unitName)]
                                        } else {
                                            const filteredUnits = filter(unitsFromProperty, { unitType: unitFilter.unitType })
                                            unitsCount += filteredUnits.length
                                            unitsByProperty[property.id] = [...unitsByProperty[property.id], ...filteredUnits.map(u => u.unitName)]
                                        }
                                    }
                                }
                            }
                            return []
                        },
                    })
                    receiversCount = await countUniqueUnitsFromResidents(unitsByProperty)
                }

                return { propertiesCount, unitsCount, receiversCount }
            },
        },
    ],

})

module.exports = {
    GetNewsItemsRecipientsCountersService,
}
