/**
 * Generated by `createschema ticket.TicketChange 'ticket:Relationship:Ticket:CASCADE;'`
 */

import {
    TicketChange,
    TicketChangeCreateInput,
    TicketChangeUpdateInput,
    QueryAllTicketChangesArgs,
} from '@app/condo/schema'
import { generateReactHooks } from '@condo/domains/common/utils/codegeneration/generate.hooks'
import { TicketChange as TicketChangeGQL } from '@condo/domains/ticket/gql'

const {
    useObject,
    useObjects,
    useCreate,
    useUpdate,
    useSoftDelete,
} = generateReactHooks<TicketChange, TicketChangeCreateInput, TicketChangeUpdateInput, QueryAllTicketChangesArgs>(TicketChangeGQL)

export {
    useObject,
    useObjects,
    useCreate,
    useUpdate,
    useSoftDelete,
}
