/**
 * Generated by `createschema billing.BillingIntegrationLog 'context:Relationship:BillingIntegrationOrganizationContext:CASCADE; type:Text; message:Text; meta:Json'`
 */

import {
    BillingIntegrationLog,
    BillingIntegrationLogCreateInput,
    BillingIntegrationLogUpdateInput,
    QueryAllBillingIntegrationLogsArgs,
} from '@app/condo/schema'
import { generateNewReactHooks } from '@condo/domains/common/utils/codegeneration/new.generate.hooks'
import { BillingIntegrationLog as BillingIntegrationLogGQL } from '@condo/domains/billing/gql'

const {
    useNewObject,
    useNewObjects,
    useNewCreate,
    useNewUpdate,
    useNewSoftDelete,
} = generateNewReactHooks<BillingIntegrationLog, BillingIntegrationLogCreateInput, BillingIntegrationLogUpdateInput, QueryAllBillingIntegrationLogsArgs>(BillingIntegrationLogGQL)

export {
    useNewObject,
    useNewObjects,
    useNewCreate,
    useNewUpdate,
    useNewSoftDelete,
}
