#to enable strict mode use pnp instead (or comment this parameter)
nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.2.cjs

packageExtensions:
  "@keystonejs/app-graphql-playground@*":
    peerDependencies:
      "graphql": "*"
  "@keystonejs/app-next@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
  "@prisma/engine-core@*":
    peerDependencies:
      "strip-ansi": "*"
  "@zeit/next-css@^1.0.1":
    peerDependencies:
      "webpack": "^4.0.0"
  "@zeit/next-less@^1.0.1":
    peerDependencies:
      "webpack": "^4.0.0"
  "antd-dayjs-webpack-plugin@*":
    "dependencies":
      "loader-utils": "^1.2.3"
  "@apollo/client@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
  "echarts-for-react@*":
    peerDependencies:
      "tslib": "*"
  "node-fetch@^2.6.0":
    dependencies:
      "encoding": "^0.1.0"
  "apollo-utilities@*":
    dependencies:
      "graphql": "^15.6.1"


