approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 7d

packageExtensions:
  "@apollo/client@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  apollo-utilities@*:
    dependencies:
      graphql: ^15.6.1
  echarts-for-react@*:
    peerDependencies:
      tslib: "*"
  node-fetch@^2.6.0:
    dependencies:
      encoding: ^0.1.0

yarnPath: .yarn/releases/yarn-4.17.0.cjs
