plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

#to enable strict mode use pnp instead (or comment this parameter)
nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.2.cjs

packageExtensions:
  "@apollo/client@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
  "echarts-for-react@*":
    peerDependencies:
      "tslib": "*"
  "node-fetch@^2.6.0":
    dependencies:
      "encoding": "^0.1.0"
  "apollo-utilities@*":
    dependencies:
      "graphql": "^15.6.1"


