approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 7d

packageExtensions:
  "@apollo/client@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
    peerDependenciesMeta:
      "@types/react-dom":
        optional: true
      react:
        optional: true
      react-dom:
        optional: true
  "@app/condo@*":
    peerDependenciesMeta:
      dd-trace:
        optional: true
  "@mono-pub/commit-analyzer@*":
    peerDependencies:
      mono-pub: "*"
  "@open-condo/codegen@*":
    peerDependenciesMeta:
      "@graphql-tools/graphql-file-loader":
        optional: true
      "@graphql-tools/load":
        optional: true
      react:
        optional: true
      react-dom:
        optional: true
      "@types/react-dom":
        optional: true
  "@open-condo/webhooks@*":
    peerDependenciesMeta:
      "@open-keystone/fields":
        optional: true
      "@graphql-tools/graphql-file-loader":
        optional: true
      "@graphql-tools/load":
        optional: true
      react:
        optional: true
      "@types/react-dom":
        optional: true
  "@rollup/plugin-babel@*":
    peerDependencies:
      rollup: "*"
  "@rollup/plugin-typescript@*":
    peerDependencies:
      rollup: "*"
  "@rollup/pluginutils@*":
    peerDependencies:
      rollup: "*"
  "@welldone-software/why-did-you-render@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "apollo-boost@*":
    peerDependencies:
      graphql: "*"
  "apollo-utilities@*":
    dependencies:
      graphql: "^15.6.1"
  "babel-loader@*":
    peerDependenciesMeta:
      webpack:
        optional: true
  "echarts-for-react@*":
    peerDependenciesMeta:
      tslib:
        optional: true
  "express-graphql@*":
    peerDependencies:
      graphql: "*"
  "flowise-embed-react@*":
    peerDependencies:
      flowise-embed: "*"
  "mini-create-react-context@*":
    peerDependencies:
      react: "*"
  "node-fetch@^2.6.0":
    dependencies:
      encoding: "^0.1.0"
  "react-progressive-image@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "react-pseudo-state@*":
    peerDependencies:
      react: "*"
  "telegraf-i18n@*":
    peerDependencies:
      telegraf: "*"

yarnPath: .yarn/releases/yarn-4.17.0.cjs
