/**
 * This file is autogenerated by `createschema test.RelationModel 'name:Text;'`
 * In most cases you should not change it by hands. And please don't remove `AUTOGENERATE MARKER`s
 */

export * as RelationModel from './RelationModel'
export * as Model from './Model'
/* AUTOGENERATE MARKER <IMPORT-EXPORT> */
