const OCCUPANCY_STATUS_PLANNED = 'planned'
const OCCUPANCY_STATUS_ACTIVE = 'active'
const OCCUPANCY_STATUS_ENDED = 'ended'
const OCCUPANCY_STATUS_CANCELED = 'canceled'

const OCCUPANCY_STATUSES = [
    OCCUPANCY_STATUS_PLANNED,
    OCCUPANCY_STATUS_ACTIVE,
    OCCUPANCY_STATUS_ENDED,
    OCCUPANCY_STATUS_CANCELED,
]

const BILLING_FREQUENCY_MONTHLY = 'monthly'
const BILLING_FREQUENCY_ANNUAL = 'annual'

const BILLING_FREQUENCIES = [
    BILLING_FREQUENCY_MONTHLY,
    BILLING_FREQUENCY_ANNUAL,
]

module.exports = {
    OCCUPANCY_STATUS_PLANNED,
    OCCUPANCY_STATUS_ACTIVE,
    OCCUPANCY_STATUS_ENDED,
    OCCUPANCY_STATUS_CANCELED,
    OCCUPANCY_STATUSES,
    BILLING_FREQUENCY_MONTHLY,
    BILLING_FREQUENCY_ANNUAL,
    BILLING_FREQUENCIES,
}
