/**
 * Generated by `createschema meter.MeterReading 'organization:Relationship:Organization:CASCADE; property:Relationship:Property:CASCADE; account?:Relationship:BillingAccount:SET_NULL; billingAccountMeter?:Relationship:BillingAccountMeter:SET_NULL; date:DateTimeUtc; meter:Relationship:Meter:CASCADE; value:Integer; source:Relationship:MeterReadingSource:PROTECT'`
 */
const { catchErrorFrom } = require('@condo/domains/common/utils/testSchema')
const { VALUE_LESS_THAN_PREVIOUS_ERROR } = require('@condo/domains/meter/constants/errors')
const { expectToThrowAuthenticationErrorToObj } = require('@condo/domains/common/utils/testSchema')
const { createTestProperty } = require('@condo/domains/property/utils/testSchema')
const { createTestOrganization } = require('@condo/domains/organization/utils/testSchema')
const { makeClientWithProperty } = require('@condo/domains/property/utils/testSchema')
const { createTestResident } = require('@condo/domains/resident/utils/testSchema')
const { makeClientWithResidentUserAndProperty } = require('@condo/domains/property/utils/testSchema')
const { updateTestOrganizationEmployee } = require('@condo/domains/organization/utils/testSchema')
const { createTestOrganizationEmployeeRole } = require('@condo/domains/organization/utils/testSchema')
const { createTestOrganizationWithAccessToAnotherOrganization } = require('@condo/domains/organization/utils/testSchema')
const { expectToThrowAccessDeniedErrorToObj } = require('@condo/domains/common/utils/testSchema')
const { createTestMeter } = require('@condo/domains/meter/utils/testSchema')
const { MeterResource, MeterReadingSource } = require('@condo/domains/meter/utils/testSchema')
const { makeEmployeeUserClientWithAbilities } = require('@condo/domains/organization/utils/testSchema')
const { makeLoggedInAdminClient, makeClient, UUID_RE, DATETIME_RE } = require('@core/keystone/test.utils')
const { MeterReading, createTestMeterReading, updateTestMeterReading } = require('@condo/domains/meter/utils/testSchema')
const moment = require('moment')

const COLD_WATER_METER_RESOURCE_ID = 'e2bd70ac-0630-11ec-9a03-0242ac130003'
const CALL_METER_READING_SOURCE_ID = '61764f14-0630-11ec-9a03-0242ac130003'

describe('MeterReading', () => {
    describe('Create', () => {
        test('employee with canManageMeters role: can create MeterReadings', async () => {
            const client = await makeEmployeeUserClientWithAbilities({
                canManageMeters: true,
            })
            const [resource] = await MeterResource.getAll(client, { id: COLD_WATER_METER_RESOURCE_ID })
            const [source] = await MeterReadingSource.getAll(client, { id: CALL_METER_READING_SOURCE_ID })
            const [meter] = await createTestMeter(client, client.organization, client.property, resource, {})

            const [meterReading] = await createTestMeterReading(client, client.organization, client.property, meter, source)

            expect(meterReading.id).toMatch(UUID_RE)
        })

        test('employee without "canManageMeters" role: cannot create MeterReadings', async () => {
            const admin = await makeLoggedInAdminClient()
            const client = await makeEmployeeUserClientWithAbilities()
            const [resource] = await MeterResource.getAll(client, { id: COLD_WATER_METER_RESOURCE_ID })
            const [source] = await MeterReadingSource.getAll(client, { id: CALL_METER_READING_SOURCE_ID })
            const [meter] = await createTestMeter(admin, client.organization, client.property, resource, {})

            await expectToThrowAccessDeniedErrorToObj(async () => {
                await createTestMeterReading(client, client.organization, client.property, meter, source)
            })
        })

        test('employee from "from" related organization with "canManageMeters" role: can create MeterReadings', async () => {
            const admin = await makeLoggedInAdminClient()
            const { clientFrom, employeeFrom, organizationFrom, organizationTo, propertyTo } = await createTestOrganizationWithAccessToAnotherOrganization()
            const [role] = await createTestOrganizationEmployeeRole(admin, organizationFrom, {
                canManageMeters: true,
            })
            await updateTestOrganizationEmployee(admin, employeeFrom.id, {
                role: { connect: { id: role.id } },
            })
            const [resource] = await MeterResource.getAll(clientFrom, { id: COLD_WATER_METER_RESOURCE_ID })
            const [source] = await MeterReadingSource.getAll(clientFrom, { id: CALL_METER_READING_SOURCE_ID })
            const [meter] = await createTestMeter(clientFrom, organizationTo, propertyTo, resource, {})

            const [meterReading] = await createTestMeterReading(clientFrom, organizationTo, propertyTo, meter, source)

            expect(meterReading.id).toMatch(UUID_RE)
        })

        test('employee from "from" related organization without "canManageMeters" role: cannot create MeterReadings', async () => {
            const admin = await makeLoggedInAdminClient()
            const { clientFrom, organizationTo, propertyTo } = await createTestOrganizationWithAccessToAnotherOrganization()
            const [resource] = await MeterResource.getAll(clientFrom, { id: COLD_WATER_METER_RESOURCE_ID })
            const [source] = await MeterReadingSource.getAll(admin, { id: CALL_METER_READING_SOURCE_ID })
            const [meter] = await createTestMeter(admin, organizationTo, propertyTo, resource, {})

            await expectToThrowAccessDeniedErrorToObj(async () => {
                await createTestMeterReading(clientFrom, organizationTo, propertyTo, meter, source)
            })
        })

        test('resident: can create MeterReadings', async () => {
            const adminClient = await makeLoggedInAdminClient()
            const client = await makeClientWithResidentUserAndProperty()
            await createTestResident(adminClient, client.user, client.organization, client.property)
            const [resource] = await MeterResource.getAll(client, { id: COLD_WATER_METER_RESOURCE_ID })
            const [source] = await MeterReadingSource.getAll(adminClient, { id: CALL_METER_READING_SOURCE_ID })
            const [meter] = await createTestMeter(client, client.organization, client.property, resource, {})

            const [meterReading] = await createTestMeterReading(client, client.organization, client.property, meter, source)

            expect(meterReading.id).toMatch(UUID_RE)
        })

        test('user: cannot create MeterReadings', async () => {
            const adminClient = await makeLoggedInAdminClient()
            const client = await makeClientWithProperty()
            const [resource] = await MeterResource.getAll(adminClient, { id: COLD_WATER_METER_RESOURCE_ID })
            const [source] = await MeterReadingSource.getAll(adminClient, { id: CALL_METER_READING_SOURCE_ID })
            const [meter] = await createTestMeter(adminClient, client.organization, client.property, resource, {})

            await expectToThrowAccessDeniedErrorToObj(async () => {
                await createTestMeterReading(client, client.organization, client.property, meter, source)
            })
        })

        test('anonymous: cannot create MeterReadings', async () => {
            const adminClient = await makeLoggedInAdminClient()
            const client = await makeClient()
            const [organization] = await createTestOrganization(adminClient)
            const [property] = await createTestProperty(adminClient, organization)
            const [source] = await MeterReadingSource.getAll(adminClient, { id: CALL_METER_READING_SOURCE_ID })
            const [resource] = await MeterResource.getAll(adminClient, { id: COLD_WATER_METER_RESOURCE_ID })
            const [meter] = await createTestMeter(adminClient, organization, property, resource, {})

            await expectToThrowAuthenticationErrorToObj(async () => {
                await createTestMeterReading(client, organization, property, meter, source)
            })
        })

        test('admin: can create MeterReadings', async () => {
            const adminClient = await makeLoggedInAdminClient()
            const [organization] = await createTestOrganization(adminClient)
            const [property] = await createTestProperty(adminClient, organization)
            const [source] = await MeterReadingSource.getAll(adminClient, { id: CALL_METER_READING_SOURCE_ID })
            const [resource] = await MeterResource.getAll(adminClient, { id: COLD_WATER_METER_RESOURCE_ID })
            const [meter] = await createTestMeter(adminClient, organization, property, resource, {})

            const [meterReading] = await createTestMeterReading(adminClient, organization, property, meter, source)

            expect(meterReading.id).toMatch(UUID_RE)
        })
    })
    describe('Update', () => {
        test('employee with canManageMeters role: can update MeterReadings', async () => {
            const client = await makeEmployeeUserClientWithAbilities({
                canManageMeters: true,
            })
            const [resource] = await MeterResource.getAll(client, { id: COLD_WATER_METER_RESOURCE_ID })
            const [source] = await MeterReadingSource.getAll(client, { id: CALL_METER_READING_SOURCE_ID })
            const [meter] = await createTestMeter(client, client.organization, client.property, resource, {})
            const [meterReading] = await createTestMeterReading(client, client.organization, client.property, meter, source)

            const oldValue = meterReading.value
            const newValue = oldValue + 100

            const [updatedMeterReading] = await updateTestMeterReading(client, meterReading.id, {
                value: newValue,
            })

            expect(updatedMeterReading.id).toMatch(UUID_RE)
            expect(updatedMeterReading.value).toEqual(newValue)
        })

        test('employee with canManageMeters role: cannot update MeterReadings with meter reading value less than previous', async () => {
            const client = await makeEmployeeUserClientWithAbilities({
                canManageMeters: true,
            })
            const [resource] = await MeterResource.getAll(client, { id: COLD_WATER_METER_RESOURCE_ID })
            const [source] = await MeterReadingSource.getAll(client, { id: CALL_METER_READING_SOURCE_ID })
            const [meter] = await createTestMeter(client, client.organization, client.property, resource, {})
            const [meterReading] = await createTestMeterReading(client, client.organization, client.property, meter, source)

            const oldValue = meterReading.value
            const newValue = oldValue - 100

            await catchErrorFrom(async () => {
                await updateTestMeterReading(client, meterReading.id, {
                    value: newValue,
                })
            }, ({ errors }) => {
                console.log(errors)
                expect(errors[0].data.messages[0]).toContain(VALUE_LESS_THAN_PREVIOUS_ERROR)
            })
        })

        test('employee without "canManageMeters" role: cannot update MeterReadings', async () => {
            const admin = await makeLoggedInAdminClient()
            const client = await makeEmployeeUserClientWithAbilities()
            const [resource] = await MeterResource.getAll(client, { id: COLD_WATER_METER_RESOURCE_ID })
            const [source] = await MeterReadingSource.getAll(client, { id: CALL_METER_READING_SOURCE_ID })
            const [meter] = await createTestMeter(admin, client.organization, client.property, resource, {})
            const [meterReading] = await createTestMeterReading(admin, client.organization, client.property, meter, source)

            const oldValue = meterReading.value
            const newValue = oldValue + 100

            await expectToThrowAccessDeniedErrorToObj(async () => {
                await updateTestMeterReading(client, meterReading.id, {
                    value: newValue,
                })
            })
        })

        test('employee from "from" related organization with "canManageMeters" role: can update MeterReadings', async () => {
            const admin = await makeLoggedInAdminClient()
            const { clientFrom, employeeFrom, organizationFrom, organizationTo, propertyTo } = await createTestOrganizationWithAccessToAnotherOrganization()
            const [role] = await createTestOrganizationEmployeeRole(admin, organizationFrom, {
                canManageMeters: true,
            })
            await updateTestOrganizationEmployee(admin, employeeFrom.id, {
                role: { connect: { id: role.id } },
            })
            const [resource] = await MeterResource.getAll(clientFrom, { id: COLD_WATER_METER_RESOURCE_ID })
            const [source] = await MeterReadingSource.getAll(clientFrom, { id: CALL_METER_READING_SOURCE_ID })
            const [meter] = await createTestMeter(clientFrom, organizationTo, propertyTo, resource, {})

            const [meterReading] = await createTestMeterReading(clientFrom, organizationTo, propertyTo, meter, source)

            const oldValue = meterReading.value
            const newValue = oldValue + 100

            const [updatedMeterReading] = await updateTestMeterReading(clientFrom, meterReading.id, {
                value: newValue,
            })

            expect(updatedMeterReading.id).toMatch(UUID_RE)
            expect(updatedMeterReading.value).toEqual(newValue)
        })

        test('employee from "from" related organization without "canManageMeters" role: cannot update MeterReadings', async () => {
            const admin = await makeLoggedInAdminClient()
            const { clientFrom, organizationTo, propertyTo } = await createTestOrganizationWithAccessToAnotherOrganization()
            const [resource] = await MeterResource.getAll(clientFrom, { id: COLD_WATER_METER_RESOURCE_ID })
            const [source] = await MeterReadingSource.getAll(admin, { id: CALL_METER_READING_SOURCE_ID })
            const [meter] = await createTestMeter(admin, organizationTo, propertyTo, resource, {})
            const [meterReading] = await createTestMeterReading(admin, organizationTo, propertyTo, meter, source)

            const oldValue = meterReading.value
            const newValue = oldValue + 100

            await expectToThrowAccessDeniedErrorToObj(async () => {
                await updateTestMeterReading(clientFrom, meterReading.id, {
                    value: newValue,
                })
            })
        })

        test('resident: cannot update MeterReadings', async () => {
            const adminClient = await makeLoggedInAdminClient()
            const client = await makeClientWithResidentUserAndProperty()
            await createTestResident(adminClient, client.user, client.organization, client.property)
            const [resource] = await MeterResource.getAll(client, { id: COLD_WATER_METER_RESOURCE_ID })
            const [source] = await MeterReadingSource.getAll(adminClient, { id: CALL_METER_READING_SOURCE_ID })
            const [meter] = await createTestMeter(client, client.organization, client.property, resource, {})
            const [meterReading] = await createTestMeterReading(client, client.organization, client.property, meter, source)

            const oldValue = meterReading.value
            const newValue = oldValue + 100
            await expectToThrowAccessDeniedErrorToObj(async () => {
                await updateTestMeterReading(client, meterReading.id, {
                    value: newValue,
                })
            })
        })

        test('user: cannot update MeterReadings', async () => {
            const adminClient = await makeLoggedInAdminClient()
            const client = await makeClientWithProperty()
            const [resource] = await MeterResource.getAll(adminClient, { id: COLD_WATER_METER_RESOURCE_ID })
            const [source] = await MeterReadingSource.getAll(adminClient, { id: CALL_METER_READING_SOURCE_ID })
            const [meter] = await createTestMeter(adminClient, client.organization, client.property, resource, {})
            const [meterReading] = await createTestMeterReading(adminClient, client.organization, client.property, meter, source)

            const oldValue = meterReading.value
            const newValue = oldValue + 100
            await expectToThrowAccessDeniedErrorToObj(async () => {
                await updateTestMeterReading(client, meterReading.id, {
                    value: newValue,
                })
            })
        })

        test('anonymous: cannot update MeterReadings', async () => {
            const adminClient = await makeLoggedInAdminClient()
            const client = await makeClient()
            const [organization] = await createTestOrganization(adminClient)
            const [property] = await createTestProperty(adminClient, organization)
            const [source] = await MeterReadingSource.getAll(adminClient, { id: CALL_METER_READING_SOURCE_ID })
            const [resource] = await MeterResource.getAll(adminClient, { id: COLD_WATER_METER_RESOURCE_ID })
            const [meter] = await createTestMeter(adminClient, organization, property, resource, {})
            const [meterReading] = await createTestMeterReading(adminClient, organization, property, meter, source)

            const oldValue = meterReading.value
            const newValue = oldValue + 100
            await expectToThrowAuthenticationErrorToObj(async () => {
                await updateTestMeterReading(client, meterReading.id, {
                    value: newValue,
                })
            })
        })

        test('admin: can update MeterReadings', async () => {
            const adminClient = await makeLoggedInAdminClient()
            const [organization] = await createTestOrganization(adminClient)
            const [property] = await createTestProperty(adminClient, organization)
            const [source] = await MeterReadingSource.getAll(adminClient, { id: CALL_METER_READING_SOURCE_ID })
            const [resource] = await MeterResource.getAll(adminClient, { id: COLD_WATER_METER_RESOURCE_ID })
            const [meter] = await createTestMeter(adminClient, organization, property, resource, {})
            const [meterReading] = await createTestMeterReading(adminClient, organization, property, meter, source)

            const oldValue = meterReading.value
            const newValue = oldValue + 100
            const [updatedMeterReading] = await updateTestMeterReading(adminClient, meterReading.id, {
                value: newValue,
            })

            expect(updatedMeterReading.id).toMatch(UUID_RE)
            expect(updatedMeterReading.value).toEqual(newValue)
        })
    })
})
