const INVALID_PHONE = 'INVALID_PHONE'
const INVALID_EMAIL = 'INVALID_EMAIL'
const INVALID_CODE = 'INVALID_CODE'
const USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS'
const CONDO_USER_ALREADY_EXISTS = 'CONDO_USER_ALREADY_EXISTS'
const ACTION_NOT_FOUND = 'ACTION_NOT_FOUND'
const PASSWORD_TOO_SIMPLE = 'PASSWORD_TOO_SIMPLE'
const SMS_DAILY_LIMIT_REACHED = 'SMS_FOR_DAY_LIMIT_REACHED'
const EMAILS_DAILY_LIMIT_REACHED = 'EMAILS_DAILY_LIMIT_REACHED'
const INCORRECT_PHONE_OR_PASSWORD = 'INVALID_PHONE_OR_PASSWORD'
const AUTH_ATTEMPTS_DAILY_LIMIT_REACHED = 'AUTH_ATTEMPTS_DAILY_LIMIT_REACHED'
const OIDC_AUTH_ERROR = 'OIDC_AUTH_ERROR'

module.exports = {
    INVALID_PHONE,
    INVALID_EMAIL,
    USER_ALREADY_EXISTS,
    ACTION_NOT_FOUND,
    PASSWORD_TOO_SIMPLE,
    SMS_DAILY_LIMIT_REACHED,
    EMAILS_DAILY_LIMIT_REACHED,
    INVALID_CODE,
    INCORRECT_PHONE_OR_PASSWORD,
    AUTH_ATTEMPTS_DAILY_LIMIT_REACHED,
    CONDO_USER_ALREADY_EXISTS,
    OIDC_AUTH_ERROR,
}