const MIN_PASSWORD_LENGTH = 12
const MIN_PASSWORD_DIFFERENT_CHARACTERS = 4

const CONFIRM_PHONE_ACTION_CODE_LENGTH = 4
const CONFIRM_PHONE_ACTION_TTL_IN_SEC = 5 * 60 // 5 min
const CONFIRM_PHONE_ACTION_DAILY_LIMIT_BY_IP = 20
const CONFIRM_PHONE_ACTION_DAILY_LIMIT_BY_PHONE = 10
const CONFIRM_PHONE_ACTION_MAX_ATTEMPTS = 5
const AUTH_WITH_PHONE_DAILY_LIMIT_BY_IP = 25

const CONFIRM_EMAIL_ACTION_CODE_LENGTH = 6
const CONFIRM_EMAIL_ACTION_TTL_IN_SEC = 5 * 60 // 5 min
const CONFIRM_EMAIL_ACTION_DAILY_LIMIT_BY_USER = 10
const CONFIRM_EMAIL_ACTION_DAILY_LIMIT_BY_EMAIL = 5
const CONFIRM_EMAIL_ACTION_MAX_ATTEMPTS = 5

module.exports = {
    MIN_PASSWORD_LENGTH,
    MIN_PASSWORD_DIFFERENT_CHARACTERS,
    CONFIRM_PHONE_ACTION_CODE_LENGTH,
    CONFIRM_PHONE_ACTION_TTL_IN_SEC,
    CONFIRM_PHONE_ACTION_DAILY_LIMIT_BY_IP,
    CONFIRM_PHONE_ACTION_DAILY_LIMIT_BY_PHONE,
    CONFIRM_PHONE_ACTION_MAX_ATTEMPTS,
    AUTH_WITH_PHONE_DAILY_LIMIT_BY_IP,
    CONFIRM_EMAIL_ACTION_CODE_LENGTH,
    CONFIRM_EMAIL_ACTION_TTL_IN_SEC,
    CONFIRM_EMAIL_ACTION_DAILY_LIMIT_BY_USER,
    CONFIRM_EMAIL_ACTION_DAILY_LIMIT_BY_EMAIL,
    CONFIRM_EMAIL_ACTION_MAX_ATTEMPTS,
}
