const DEFAULT_PAGE_SIZE = 30
const COLUMN_ID_SELECTION = 'selection'
const DEFAULT_MIN_SIZE = 70
const PAGINATION_CONSTANTS = {
    MAX_VISIBLE_PAGES: 7,
    PAGES_JUMP: 5,
    FIRST_PAGE: 1,
    PAGINATION_THRESHOLD: 4,
} as const


export { 
    DEFAULT_PAGE_SIZE,
    COLUMN_ID_SELECTION,
    DEFAULT_MIN_SIZE,
    PAGINATION_CONSTANTS,
}