const TICKET_STEP_TYPE = 'ticket'
const BILLING_STEP_TYPE = 'billing'
const METER_STEP_TYPE = 'meter'
const RESIDENT_STEP_TYPE = 'resident'
const CREATE_PROPERTY_STEP_TYPE = 'createProperty'
const CREATE_PROPERTY_MAP_STEP_TYPE = 'createPropertyMap'
const CREATE_TICKET_STEP_TYPE = 'createTicket'
const NOTIFY_RESIDENTS_ABOUT_TICKETS_STEP_TYPE = 'notifyResidentsAboutTickets'
const UPLOAD_RECEIPTS_STEP_TYPE = 'uploadReceipts'
const NOTIFY_RESIDENTS_ABOUT_PAYMENTS_STEP_TYPE = 'notifyResidentsAboutPayments'
const CREATE_METER_READINGS_STEP_TYPE = 'createMeterReadings'
const NOTIFY_RESIDENTS_ABOUT_METER_READINGS_STEP_TYPE = 'notifyResidentsAboutMeterReadings'
const VIEW_RESIDENT_APP_GUIDE_STEP_TYPE = 'viewResidentsAppGuide'
const CREATE_NEWS_STEP_TYPE = 'createNews'

const STEP_TYPES = [
    TICKET_STEP_TYPE,
    BILLING_STEP_TYPE,
    METER_STEP_TYPE,
    RESIDENT_STEP_TYPE,
    CREATE_PROPERTY_STEP_TYPE,
    CREATE_PROPERTY_MAP_STEP_TYPE,
    CREATE_TICKET_STEP_TYPE,
    NOTIFY_RESIDENTS_ABOUT_TICKETS_STEP_TYPE,
    UPLOAD_RECEIPTS_STEP_TYPE,
    NOTIFY_RESIDENTS_ABOUT_PAYMENTS_STEP_TYPE,
    CREATE_METER_READINGS_STEP_TYPE,
    NOTIFY_RESIDENTS_ABOUT_METER_READINGS_STEP_TYPE,
    VIEW_RESIDENT_APP_GUIDE_STEP_TYPE,
    CREATE_NEWS_STEP_TYPE,
]

const STEP_TRANSITIONS = {
    [TICKET_STEP_TYPE]: [CREATE_PROPERTY_STEP_TYPE, CREATE_PROPERTY_MAP_STEP_TYPE, CREATE_TICKET_STEP_TYPE, NOTIFY_RESIDENTS_ABOUT_TICKETS_STEP_TYPE],
    [BILLING_STEP_TYPE]: [UPLOAD_RECEIPTS_STEP_TYPE, NOTIFY_RESIDENTS_ABOUT_PAYMENTS_STEP_TYPE],
    [METER_STEP_TYPE]: [CREATE_PROPERTY_STEP_TYPE, CREATE_PROPERTY_MAP_STEP_TYPE, CREATE_METER_READINGS_STEP_TYPE, NOTIFY_RESIDENTS_ABOUT_METER_READINGS_STEP_TYPE],
    [RESIDENT_STEP_TYPE]: [CREATE_PROPERTY_STEP_TYPE, CREATE_PROPERTY_MAP_STEP_TYPE, VIEW_RESIDENT_APP_GUIDE_STEP_TYPE, CREATE_NEWS_STEP_TYPE],
}

const INITIAL_ENABLED_STEPS = [TICKET_STEP_TYPE, BILLING_STEP_TYPE, METER_STEP_TYPE, CREATE_PROPERTY_STEP_TYPE, UPLOAD_RECEIPTS_STEP_TYPE, CREATE_PROPERTY_STEP_TYPE]

const ENABLED_STEPS_AFTER_COMPLETE = {
    [BILLING_STEP_TYPE]: [RESIDENT_STEP_TYPE],
    [CREATE_PROPERTY_STEP_TYPE]: [CREATE_PROPERTY_MAP_STEP_TYPE],
    [CREATE_PROPERTY_MAP_STEP_TYPE]: [CREATE_TICKET_STEP_TYPE, CREATE_METER_READINGS_STEP_TYPE, VIEW_RESIDENT_APP_GUIDE_STEP_TYPE],
    [CREATE_TICKET_STEP_TYPE]: [NOTIFY_RESIDENTS_ABOUT_TICKETS_STEP_TYPE],
    [UPLOAD_RECEIPTS_STEP_TYPE]: [NOTIFY_RESIDENTS_ABOUT_PAYMENTS_STEP_TYPE],
    [CREATE_METER_READINGS_STEP_TYPE]: [NOTIFY_RESIDENTS_ABOUT_METER_READINGS_STEP_TYPE],
    [VIEW_RESIDENT_APP_GUIDE_STEP_TYPE]: [CREATE_NEWS_STEP_TYPE],
}

const STEP_ORDER = {
    [TICKET_STEP_TYPE]: 1,
    [BILLING_STEP_TYPE]: 2,
    [METER_STEP_TYPE]: 3,
    [RESIDENT_STEP_TYPE]: 4,
    [CREATE_PROPERTY_STEP_TYPE]: 1,
    [CREATE_PROPERTY_MAP_STEP_TYPE]: 2,
    [CREATE_TICKET_STEP_TYPE]: 3,
    [NOTIFY_RESIDENTS_ABOUT_TICKETS_STEP_TYPE]: 4,
    [UPLOAD_RECEIPTS_STEP_TYPE]: 1,
    [NOTIFY_RESIDENTS_ABOUT_PAYMENTS_STEP_TYPE]: 2,
    [CREATE_METER_READINGS_STEP_TYPE]: 3,
    [NOTIFY_RESIDENTS_ABOUT_METER_READINGS_STEP_TYPE]: 4,
    [VIEW_RESIDENT_APP_GUIDE_STEP_TYPE]: 3,
    [CREATE_NEWS_STEP_TYPE]: 4,
}

const TODO_STEP_STATUS = 'todo'
const WAITING_STEP_STATUS = 'waiting'
const DISABLED_STEP_STATUS = 'disabled'
const COMPLETED_STEP_STATUS = 'completed'

const STEP_STATUSES = [TODO_STEP_STATUS, WAITING_STEP_STATUS, DISABLED_STEP_STATUS, COMPLETED_STEP_STATUS]

const AVAILABLE_TO_UPDATE_FIELDS = ['status', 'order']

module.exports = {
    STEP_TYPES,
    STEP_TRANSITIONS,
    INITIAL_ENABLED_STEPS,
    ENABLED_STEPS_AFTER_COMPLETE,
    STEP_ORDER,
    STEP_STATUSES,
    TODO_STEP_STATUS,
    WAITING_STEP_STATUS,
    DISABLED_STEP_STATUS,
    COMPLETED_STEP_STATUS,
    TICKET_STEP_TYPE,
    BILLING_STEP_TYPE,
    METER_STEP_TYPE,
    RESIDENT_STEP_TYPE,
    CREATE_PROPERTY_STEP_TYPE,
    CREATE_PROPERTY_MAP_STEP_TYPE,
    CREATE_TICKET_STEP_TYPE,
    NOTIFY_RESIDENTS_ABOUT_TICKETS_STEP_TYPE,
    UPLOAD_RECEIPTS_STEP_TYPE,
    NOTIFY_RESIDENTS_ABOUT_PAYMENTS_STEP_TYPE,
    CREATE_METER_READINGS_STEP_TYPE,
    NOTIFY_RESIDENTS_ABOUT_METER_READINGS_STEP_TYPE,
    VIEW_RESIDENT_APP_GUIDE_STEP_TYPE,
    CREATE_NEWS_STEP_TYPE,
    AVAILABLE_TO_UPDATE_FIELDS,
}