const CALLBACK_TYPE = 'callback'
const IMPORT_FILE_TYPE = 'importFile'
const INTEGRATION_SETUP_TYPE = 'integrationSetup'
const ACTIVATE_SUBSCRIPTION_TYPE = 'activateSubscription'
const ACTIVATE_BANKING_TYPE = 'activateBanking'

const USER_HELP_REQUEST_TYPES = [
    CALLBACK_TYPE,
    IMPORT_FILE_TYPE,
    INTEGRATION_SETUP_TYPE,
    ACTIVATE_SUBSCRIPTION_TYPE,
    ACTIVATE_BANKING_TYPE,
]

const USER_HELP_REQUEST_FOLDER_NAME = 'UserHelpRequest'

module.exports = {
    CALLBACK_TYPE,
    IMPORT_FILE_TYPE,
    INTEGRATION_SETUP_TYPE,
    ACTIVATE_SUBSCRIPTION_TYPE,
    ACTIVATE_BANKING_TYPE,
    USER_HELP_REQUEST_TYPES,
    USER_HELP_REQUEST_FOLDER_NAME,
}