const recurrentPaymentConf = process.env['RECURRENT_PAYMENT'] && JSON.parse(process.env['RECURRENT_PAYMENT']) || {
    pageSize: 10,
}

const {
    pageSize,
} = recurrentPaymentConf

const paginationConfiguration = { pageSize }
const dvAndSender = { dv: 1, sender: { dv: 1, fingerprint: 'recurrent-payment-processing' } }

const PAYMENT_ERROR_UNKNOWN_CODE = 'UNKNOWN'
const PAYMENT_ERROR_LIMIT_EXCEEDED_CODE = 'LIMIT_EXCEEDED'
const PAYMENT_ERROR_CONTEXT_NOT_FOUND_CODE = 'CONTEXT_NOT_FOUND'
const PAYMENT_ERROR_CONTEXT_DISABLED_CODE = 'CONTEXT_DISABLED'
const PAYMENT_ERROR_CARD_TOKEN_NOT_VALID_CODE = 'CARD_TOKEN_NOT_VALID'
const PAYMENT_ERROR_ACQUIRING_PAYMENT_PROCEED_FAILED_CODE = 'ACQUIRING_PAYMENT_PROCEED_FAILED'
const PAYMENT_ERROR_CAN_NOT_REGISTER_MULTI_PAYMENT_CODE = 'CAN_NOT_REGISTER_MULTI_PAYMENT'

module.exports = {
    dvAndSender,
    paginationConfiguration,
    PAYMENT_ERROR_UNKNOWN_CODE,
    PAYMENT_ERROR_LIMIT_EXCEEDED_CODE,
    PAYMENT_ERROR_CONTEXT_NOT_FOUND_CODE,
    PAYMENT_ERROR_CONTEXT_DISABLED_CODE,
    PAYMENT_ERROR_CARD_TOKEN_NOT_VALID_CODE,
    PAYMENT_ERROR_ACQUIRING_PAYMENT_PROCEED_FAILED_CODE,
    PAYMENT_ERROR_CAN_NOT_REGISTER_MULTI_PAYMENT_CODE,
}