const KEYWORDS_SPECIAL_SYMBOLS_REGEX = /[!@#$%^&*)(+=.,\-_:;"'`[\]]/g
/**
 * @type {string}
 */
const OVERRIDING_ROOT = 'meta.data'

//
// ERRORS
//
const SOURCE_ALREADY_EXISTS_ERROR = 'SOURCE_ALREADY_EXISTS_ERROR'
const EMPTY_SOURCE = 'EMPTY_SOURCE'
const EMPTY_ADDRESS = 'EMPTY_ADDRESS'
const INCORRECT_ADDRESS_SOURCE = 'INCORRECT_ADDRESS_SOURCE'

module.exports = {
    KEYWORDS_SPECIAL_SYMBOLS_REGEX,
    SOURCE_ALREADY_EXISTS_ERROR,
    OVERRIDING_ROOT,
    EMPTY_SOURCE,
    EMPTY_ADDRESS,
    INCORRECT_ADDRESS_SOURCE,
}
