const RESIDENT_SUGGEST_SERVICE_PROVIDER_WINDOW_IN_SEC = 60 * 60 // 1 hour in seconds
const MAX_RESIDENT_SUGGEST_SERVICE_PROVIDER_CALLS_BY_WINDOW_SEC = 100

module.exports = {
    RESIDENT_SUGGEST_SERVICE_PROVIDER_WINDOW_IN_SEC,
    MAX_RESIDENT_SUGGEST_SERVICE_PROVIDER_CALLS_BY_WINDOW_SEC,
}