const RESIDENT_CALCULATE_FEE_FOR_RECEIPT_WINDOW_IN_SEC = 60 * 60 // 1 hour in seconds
const MAX_RESIDENT_CALCULATE_FEE_FOR_RECEIPT_WINDOW_IN_SEC_CALLS_BY_WINDOW_SEC = 100
const FIND_PAYMENTS_CHUNK_SIZE = 100

module.exports = {
    RESIDENT_CALCULATE_FEE_FOR_RECEIPT_WINDOW_IN_SEC,
    MAX_RESIDENT_CALCULATE_FEE_FOR_RECEIPT_WINDOW_IN_SEC_CALLS_BY_WINDOW_SEC,
    FIND_PAYMENTS_CHUNK_SIZE,
}