const CONTEXT_IN_PROGRESS_STATUS = 'InProgress'
const CONTEXT_VERIFICATION_STATUS = 'Verification'
const CONTEXT_ERROR_STATUS = 'Error'
const CONTEXT_FINISHED_STATUS = 'Finished'

const CONTEXT_STATUSES = [
    CONTEXT_IN_PROGRESS_STATUS,
    CONTEXT_VERIFICATION_STATUS,
    CONTEXT_ERROR_STATUS,
    CONTEXT_FINISHED_STATUS,
]

const TAX_REGIME_GENEGAL = 'general'
const TAX_REGIME_SIMPLE = 'simple'
const TAX_REGIMES = [TAX_REGIME_GENEGAL, TAX_REGIME_SIMPLE]

module.exports = {
    CONTEXT_IN_PROGRESS_STATUS,
    CONTEXT_VERIFICATION_STATUS,
    CONTEXT_ERROR_STATUS,
    CONTEXT_FINISHED_STATUS,
    CONTEXT_STATUSES,
    TAX_REGIME_GENEGAL,
    TAX_REGIME_SIMPLE,
    TAX_REGIMES,
}
