const CONTEXT_IN_PROGRESS_STATUS = 'InProgress'
const CONTEXT_VERIFICATION_STATUS = 'Verification'
const CONTEXT_ERROR_STATUS = 'Error'
const CONTEXT_FINISHED_STATUS = 'Finished'

const CONTEXT_STATUSES = [
    CONTEXT_IN_PROGRESS_STATUS,
    CONTEXT_VERIFICATION_STATUS,
    CONTEXT_ERROR_STATUS,
    CONTEXT_FINISHED_STATUS,
]

module.exports = {
    CONTEXT_IN_PROGRESS_STATUS,
    CONTEXT_VERIFICATION_STATUS,
    CONTEXT_ERROR_STATUS,
    CONTEXT_FINISHED_STATUS,
    CONTEXT_STATUSES,
}