const FEE_DISTRIBUTION_FIELD_NAME = 'FeeDistributionField'
const FEE_DISTRIBUTION_INPUT_NAME = 'FeeDistributionFieldInput'
const FEE_DISTRIBUTION_SCHEMA_FIELD_NAME = `[${FEE_DISTRIBUTION_FIELD_NAME}!]!`
const FEE_DISTRIBUTION_SCHEMA_INPUT_NAME = `[${FEE_DISTRIBUTION_INPUT_NAME}!]`

module.exports = {
    FEE_DISTRIBUTION_FIELD_NAME,
    FEE_DISTRIBUTION_INPUT_NAME,
    FEE_DISTRIBUTION_SCHEMA_FIELD_NAME,
    FEE_DISTRIBUTION_SCHEMA_INPUT_NAME,
}
