const DEFAULT_ACQUIRING_INTEGRATION_NAME = 'default'

const ACQUIRING_INTEGRATION_ONLINE_PROCESSING_TYPE = 'ONLINE_PROCESSING'
const ACQUIRING_INTEGRATION_EXTERNAL_IMPORT_TYPE = 'EXTERNAL_IMPORT'

const ACQUIRING_INTEGRATION_TYPES = [ACQUIRING_INTEGRATION_ONLINE_PROCESSING_TYPE, ACQUIRING_INTEGRATION_EXTERNAL_IMPORT_TYPE]

module.exports = {
    DEFAULT_ACQUIRING_INTEGRATION_NAME,
    ACQUIRING_INTEGRATION_ONLINE_PROCESSING_TYPE,
    ACQUIRING_INTEGRATION_EXTERNAL_IMPORT_TYPE,
    ACQUIRING_INTEGRATION_TYPES,
}