// processing recurrent payment errors
const RECURRENT_PAYMENT_PROCESS_ERROR_UNKNOWN_CODE = 'UNKNOWN'
const RECURRENT_PAYMENT_PROCESS_ERROR_SERVICE_CONSUMER_NOT_FOUND_CODE = 'SERVICE_CONSUMER_NOT_FOUND'
const RECURRENT_PAYMENT_PROCESS_ERROR_LIMIT_EXCEEDED_CODE = 'LIMIT_EXCEEDED'
const RECURRENT_PAYMENT_PROCESS_ERROR_CONTEXT_NOT_FOUND_CODE = 'CONTEXT_NOT_FOUND'
const RECURRENT_PAYMENT_PROCESS_ERROR_CONTEXT_DISABLED_CODE = 'CONTEXT_DISABLED'
const RECURRENT_PAYMENT_PROCESS_ERROR_CARD_TOKEN_NOT_VALID_CODE = 'CARD_TOKEN_NOT_VALID'
const RECURRENT_PAYMENT_PROCESS_ERROR_ACQUIRING_PAYMENT_PROCEED_FAILED_CODE = 'ACQUIRING_PAYMENT_PROCEED_FAILED'
const RECURRENT_PAYMENT_PROCESS_ERROR_CAN_NOT_REGISTER_MULTI_PAYMENT_CODE = 'CAN_NOT_REGISTER_MULTI_PAYMENT'
const RECURRENT_PAYMENT_PROCESS_ERROR_NO_RECEIPTS_TO_PROCEED_CODE = 'NO_RECEIPTS_TO_PROCEED'

// list of recurrent payment statuses
const RECURRENT_PAYMENT_INIT_STATUS = 'CREATED'
const RECURRENT_PAYMENT_PROCESSING_STATUS = 'PROCESSING'
const RECURRENT_PAYMENT_DONE_STATUS = 'DONE'
const RECURRENT_PAYMENT_ERROR_NEED_RETRY_STATUS = 'ERROR_NEED_RETRY'
const RECURRENT_PAYMENT_ERROR_STATUS = 'ERROR'
const RECURRENT_PAYMENT_CANCEL_STATUS = 'CANCEL'

const RECURRENT_PAYMENT_STATUSES = [
    RECURRENT_PAYMENT_INIT_STATUS,
    RECURRENT_PAYMENT_PROCESSING_STATUS,
    RECURRENT_PAYMENT_DONE_STATUS,
    RECURRENT_PAYMENT_ERROR_NEED_RETRY_STATUS,
    RECURRENT_PAYMENT_ERROR_STATUS,
    RECURRENT_PAYMENT_CANCEL_STATUS,
]

// TODO DOMA-11572
const INSURANCE_BILLING_CATEGORY = '55dd01e4-a87c-4713-8a91-951516b543f3'

module.exports = {
    RECURRENT_PAYMENT_INIT_STATUS,
    RECURRENT_PAYMENT_PROCESSING_STATUS,
    RECURRENT_PAYMENT_DONE_STATUS,
    RECURRENT_PAYMENT_ERROR_NEED_RETRY_STATUS,
    RECURRENT_PAYMENT_ERROR_STATUS,
    RECURRENT_PAYMENT_CANCEL_STATUS,
    RECURRENT_PAYMENT_STATUSES,
    RECURRENT_PAYMENT_PROCESS_ERROR_UNKNOWN_CODE,
    RECURRENT_PAYMENT_PROCESS_ERROR_SERVICE_CONSUMER_NOT_FOUND_CODE,
    RECURRENT_PAYMENT_PROCESS_ERROR_LIMIT_EXCEEDED_CODE,
    RECURRENT_PAYMENT_PROCESS_ERROR_CONTEXT_NOT_FOUND_CODE,
    RECURRENT_PAYMENT_PROCESS_ERROR_CONTEXT_DISABLED_CODE,
    RECURRENT_PAYMENT_PROCESS_ERROR_CARD_TOKEN_NOT_VALID_CODE,
    RECURRENT_PAYMENT_PROCESS_ERROR_ACQUIRING_PAYMENT_PROCEED_FAILED_CODE,
    RECURRENT_PAYMENT_PROCESS_ERROR_CAN_NOT_REGISTER_MULTI_PAYMENT_CODE,
    RECURRENT_PAYMENT_PROCESS_ERROR_NO_RECEIPTS_TO_PROCEED_CODE,
    INSURANCE_BILLING_CATEGORY,
}
