// processing recurrent payment errors
const PAYMENT_ERROR_UNKNOWN_CODE = 'UNKNOWN'
const PAYMENT_ERROR_LIMIT_EXCEEDED_CODE = 'LIMIT_EXCEEDED'
const PAYMENT_ERROR_CONTEXT_NOT_FOUND_CODE = 'CONTEXT_NOT_FOUND'
const PAYMENT_ERROR_CONTEXT_DISABLED_CODE = 'CONTEXT_DISABLED'
const PAYMENT_ERROR_CARD_TOKEN_NOT_VALID_CODE = 'CARD_TOKEN_NOT_VALID'
const PAYMENT_ERROR_ACQUIRING_PAYMENT_PROCEED_FAILED_CODE = 'ACQUIRING_PAYMENT_PROCEED_FAILED'
const PAYMENT_ERROR_CAN_NOT_REGISTER_MULTI_PAYMENT_CODE = 'CAN_NOT_REGISTER_MULTI_PAYMENT'

// list of recurrent payment statuses
const RECURRENT_PAYMENT_INIT_STATUS = 'CREATED'
const RECURRENT_PAYMENT_PROCESSING_STATUS = 'PROCESSING'
const RECURRENT_PAYMENT_DONE_STATUS = 'DONE'
const RECURRENT_PAYMENT_ERROR_NEED_RETRY_STATUS = 'ERROR_NEED_RETRY'
const RECURRENT_PAYMENT_ERROR_STATUS = 'ERROR'
const RECURRENT_PAYMENT_CANCEL_STATUS = 'CANCEL'

const RECURRENT_PAYMENT_STATUSES = [
    RECURRENT_PAYMENT_INIT_STATUS,
    RECURRENT_PAYMENT_PROCESSING_STATUS,
    RECURRENT_PAYMENT_DONE_STATUS,
    RECURRENT_PAYMENT_ERROR_NEED_RETRY_STATUS,
    RECURRENT_PAYMENT_ERROR_STATUS,
    RECURRENT_PAYMENT_CANCEL_STATUS,
]

module.exports = {
    RECURRENT_PAYMENT_INIT_STATUS,
    RECURRENT_PAYMENT_PROCESSING_STATUS,
    RECURRENT_PAYMENT_DONE_STATUS,
    RECURRENT_PAYMENT_ERROR_NEED_RETRY_STATUS,
    RECURRENT_PAYMENT_ERROR_STATUS,
    RECURRENT_PAYMENT_CANCEL_STATUS,
    RECURRENT_PAYMENT_STATUSES,
    PAYMENT_ERROR_UNKNOWN_CODE,
    PAYMENT_ERROR_LIMIT_EXCEEDED_CODE,
    PAYMENT_ERROR_CONTEXT_NOT_FOUND_CODE,
    PAYMENT_ERROR_CONTEXT_DISABLED_CODE,
    PAYMENT_ERROR_CARD_TOKEN_NOT_VALID_CODE,
    PAYMENT_ERROR_ACQUIRING_PAYMENT_PROCEED_FAILED_CODE,
    PAYMENT_ERROR_CAN_NOT_REGISTER_MULTI_PAYMENT_CODE,
}
