const { GQLErrorCode: { BAD_USER_INPUT } } = require('@open-condo/keystone/errors')

const {
    MULTIPLE_ACQUIRING_INTEGRATION,
    RECEIPTS_HAVE_NEGATIVE_TO_PAY_VALUE,
    ACQUIRING_INTEGRATION_DOES_NOT_SUPPORTS_BILLING_INTEGRATION,
    RECEIPTS_HAS_MULTIPLE_CURRENCIES,
    BILLING_RECEIPT_DOES_NOT_HAVE_COMMON_BILLING_ACCOUNT_WITH_SERVICE_CONSUMER,
    ACQUIRING_INTEGRATION_CONTEXT_IS_MISSING,
    RECEIPTS_CANNOT_BE_GROUPED_BY_ACQUIRING_INTEGRATION,
    CANNOT_FIND_ALL_BILLING_RECEIPTS,
    INVOICES_ARE_NOT_PUBLISHED,
    INVOICES_NOT_OWNED_BY_USER,
    INVOICE_CONTEXT_NOT_FINISHED,
    MULTIPAYMENT_RECEIPTS_WITH_INVOICES_FORBIDDEN,
    GQL_ERRORS: { PAYMENT_AMOUNT_LESS_THAN_MINIMUM, PAYMENT_AMOUNT_GREATER_THAN_MAXIMUM },
    FULL_PAYMENT_AMOUNT_MISMATCH,
    CANNOT_FIND_ALL_INVOICES,
    INVALID_REQUEST_MODE,
} = require('@condo/domains/acquiring/constants/errors')
const {
    REQUIRED,
    NOT_UNIQUE,
    NOT_FOUND,
    DV_VERSION_MISMATCH,
    WRONG_VALUE,
    WRONG_FORMAT,
} = require('@condo/domains/common/constants/errors')

const REGISTER_MULTI_PAYMENT_ERRORS = {
    DV_VERSION_MISMATCH: {
        mutation: 'registerMultiPayment',
        variable: ['data', 'dv'],
        code: BAD_USER_INPUT,
        type: DV_VERSION_MISMATCH,
        message: 'Wrong value for data version number',
    },
    WRONG_SENDER_FORMAT: {
        mutation: 'registerMultiPayment',
        variable: ['data', 'sender'],
        code: BAD_USER_INPUT,
        type: WRONG_FORMAT,
        message: 'Invalid format of "sender" field value. {details}',
        correctExample: '{ "dv": 1, "fingerprint": "uniq-device-or-container-id" }',
        messageInterpolation: { details: 'Please, check the example for details' },
    },
    MISSING_REQUIRED_INPUT_DATA: {
        mutation: 'registerMultiPayment',
        code: BAD_USER_INPUT,
        type: REQUIRED,
        message: 'Missing required value for "groupedReceipts" field and/or for "invoices" field',
    },
    MISSING_REQUIRED_RECEIPTS_IN_GROUPED_RECEIPTS: {
        mutation: 'registerMultiPayment',
        variable: ['data', 'groupedReceipts', '[]', 'receipts'],
        code: BAD_USER_INPUT,
        type: REQUIRED,
        message: 'Each group of receipts should contain at least 1 receipt',
    },
    DUPLICATED_SERVICE_CONSUMER: {
        mutation: 'registerMultiPayment',
        variable: ['data', 'groupedReceipts', '[]', 'serviceConsumer', 'id'],
        code: BAD_USER_INPUT,
        type: NOT_UNIQUE,
        message: 'There are some groupedReceipts with same serviceConsumer',
    },
    DUPLICATED_RECEIPT: {
        mutation: 'registerMultiPayment',
        variable: ['data', 'groupedReceipts', '[]', 'receipts'],
        code: BAD_USER_INPUT,
        type: NOT_UNIQUE,
        message: 'Found duplicated receipt ids. Note, each receipt can only occur in single ServiceConsumer per mutation run and cannot be noticed twice',
    },
    BAD_AMOUNT_DISTRIBUTION_FOR_RECEIPTS: {
        mutation: 'registerMultiPayment',
        variable: ['data', 'groupedReceipts', '[]', 'amountDistribution'],
        code: BAD_USER_INPUT,
        type: WRONG_VALUE,
        message: 'Amount distribution should include all receipts in a request',
    },
    PAYMENT_AMOUNT_LESS_THAN_MINIMUM: {
        ...PAYMENT_AMOUNT_LESS_THAN_MINIMUM,
        mutation: 'registerMultiPayment',
    },
    PAYMENT_AMOUNT_GREATER_THAN_MAXIMUM: {
        ...PAYMENT_AMOUNT_GREATER_THAN_MAXIMUM,
        mutation: 'registerMultiPayment',
    },
    DUPLICATED_INVOICE: {
        mutation: 'registerMultiPayment',
        variable: ['data', 'invoices'],
        code: BAD_USER_INPUT,
        type: NOT_UNIQUE,
        message: 'Found duplicated invoices.',
    },
    UNPUBLISHED_INVOICE: {
        mutation: 'registerMultiPayment',
        variable: ['data', 'invoices'],
        code: BAD_USER_INPUT,
        type: INVOICES_ARE_NOT_PUBLISHED,
        message: 'Found invoices with not "published" status',
    },
    INVOICES_NOT_OWNED_BY_USER: {
        mutation: 'registerMultiPayment',
        variable: ['data', 'invoices'],
        code: BAD_USER_INPUT,
        type: INVOICES_NOT_OWNED_BY_USER,
        message: 'Found invoices not related to the current user',
    },
    INVOICE_CONTEXT_NOT_FINISHED: {
        mutation: 'registerMultiPayment',
        variable: ['data', 'invoices'],
        code: BAD_USER_INPUT,
        type: INVOICE_CONTEXT_NOT_FINISHED,
        message: 'Invoice context is not finished',
    },
    MISSING_SERVICE_CONSUMERS: {
        mutation: 'registerMultiPayment',
        variable: ['data', 'groupedReceipts', '[]', 'serviceConsumer', 'id'],
        code: BAD_USER_INPUT,
        type: NOT_FOUND,
        message: 'Cannot find specified ServiceConsumers with following ids: {ids}',
    },
    SERVICE_CONSUMERS_NOT_OWNED_BY_USER: {
        mutation: 'registerMultiPayment',
        variable: ['data', 'groupedReceipts', '[]', 'serviceConsumer', 'id'],
        code: BAD_USER_INPUT,
        type: WRONG_VALUE,
        message: 'Found ServiceConsumers not related to the current user',
    },
    ACQUIRING_INTEGRATION_CONTEXT_IS_MISSING: {
        mutation: 'registerMultiPayment',
        variable: ['data', 'groupedReceipts', '[]', 'serviceConsumer', 'id'],
        code: BAD_USER_INPUT,
        type: ACQUIRING_INTEGRATION_CONTEXT_IS_MISSING,
        message: 'ServiceConsumers with ids {ids} is not linked to AcquiringIntegrationContext',
    },
    MULTIPLE_ACQUIRING_INTEGRATION: {
        mutation: 'registerMultiPayment',
        variable: ['data', 'groupedReceipts', '[]', 'serviceConsumer', 'id'],
        code: BAD_USER_INPUT,
        type: MULTIPLE_ACQUIRING_INTEGRATION,
        message: 'Listed serviceConsumers are linked to different acquiring integrations',
    },
    RECEIPTS_CANNOT_BE_GROUPED_BY_ACQUIRING_INTEGRATION: {
        mutation: 'registerMultiPayment',
        variable: ['data', 'groupedReceipts', '[]', 'serviceConsumer', 'id'],
        code: BAD_USER_INPUT,
        type: RECEIPTS_CANNOT_BE_GROUPED_BY_ACQUIRING_INTEGRATION,
        message: 'Receipts cannot be grouped by AcquiringIntegration with id "{id}", because a value of "canGroupReceipts" field is false',
    },
    CANNOT_FIND_ALL_RECEIPTS: {
        mutation: 'registerMultiPayment',
        variable: ['data', 'groupedReceipts', '[]', 'receipts', '[]', 'id'],
        code: BAD_USER_INPUT,
        type: CANNOT_FIND_ALL_BILLING_RECEIPTS,
        message: 'Cannot find all specified BillingReceipts with ids {missingReceiptIds}',
    },
    RECEIPTS_HAVE_NEGATIVE_TO_PAY_VALUE: {
        mutation: 'registerMultiPayment',
        variable: ['data', 'groupedReceipts', '[]', 'receipts', '[]', 'id'],
        code: BAD_USER_INPUT,
        type: RECEIPTS_HAVE_NEGATIVE_TO_PAY_VALUE,
        message: 'Cannot pay for BillingReceipts {ids} with negative "toPay" value',
    },
    RECEIPT_DOES_NOT_HAVE_COMMON_BILLING_ACCOUNT_WITH_SERVICE_CONSUMER: {
        mutation: 'registerMultiPayment',
        variable: ['data', 'groupedReceipts', '[]', 'receipts', '[]', 'id'],
        code: BAD_USER_INPUT,
        type: BILLING_RECEIPT_DOES_NOT_HAVE_COMMON_BILLING_ACCOUNT_WITH_SERVICE_CONSUMER,
        message: 'BillingReceipt with id "{receiptId}" does not have common BillingAccount with specified ServiceConsumer with id "{serviceConsumerId}"',
    },
    ACQUIRING_INTEGRATION_DOES_NOT_SUPPORTS_BILLING_INTEGRATION: {
        mutation: 'registerMultiPayment',
        variable: ['data', 'groupedReceipts', '[]', 'receipts', '[]', 'id'],
        code: BAD_USER_INPUT,
        type: ACQUIRING_INTEGRATION_DOES_NOT_SUPPORTS_BILLING_INTEGRATION,
        message: 'Some of ServiceConsumer\'s AcquiringIntegration does not supports following BillingReceipt\'s BillingIntegrations: {unsupportedBillingIntegrations}',
    },
    RECEIPTS_HAS_MULTIPLE_CURRENCIES: {
        mutation: 'registerMultiPayment',
        variable: ['data', 'groupedReceipts', '[]', 'receipts', '[]', 'id'],
        code: BAD_USER_INPUT,
        type: RECEIPTS_HAS_MULTIPLE_CURRENCIES,
        message: 'BillingReceipts has multiple currencies',
    },
    RECURRENT_PAYMENT_CONTEXT_NOT_FOUND: {
        mutation: 'registerMultiPayment',
        variable: ['data', 'recurrentPaymentContext', 'id'],
        code: BAD_USER_INPUT,
        type: NOT_FOUND,
        message: 'Cannot find specified RecurrentPaymentContext with following id: {id}',
    },
    RECURRENT_PAYMENT_CONTEXT_FORBIDDEN_FOR_INVOICES: {
        mutation: 'registerMultiPayment',
        variable: ['data', 'recurrentPaymentContext', 'id'],
        code: BAD_USER_INPUT,
        type: WRONG_VALUE,
        message: 'RecurrentPaymentContext is forbidden for invoice-only payments',
    },
    RECEIPTS_WITH_INVOICES_FORBIDDEN: {
        code: BAD_USER_INPUT,
        type: MULTIPAYMENT_RECEIPTS_WITH_INVOICES_FORBIDDEN,
        message: 'Receipts and invoices are forbidden to be together',
        messageForUser: 'api.acquiring.multiPayment.RECEIPTS_WITH_INVOICES_FORBIDDEN',
    },
    FULL_PAYMENT_AMOUNT_MISMATCH: {
        code: BAD_USER_INPUT,
        type: FULL_PAYMENT_AMOUNT_MISMATCH,
        message: 'Different amount and toPay from receipt are forbidden for receipt with Billing Category that has requiresFullPayment set to true',
        messageForUser: 'api.acquiring.multiPayment.FULL_PAYMENT_AMOUNT_MISMATCH',
    },
    PAYMENT_AMOUNT_NOT_POSITIVE: {
        mutation: 'registerMultiPayment',
        variable: ['data'],
        code: BAD_USER_INPUT,
        type: WRONG_VALUE,
        message: 'All payment amounts must be positive (> 0)',
    },
    CANNOT_FIND_ALL_INVOICES: {
        mutation: 'registerMultiPayment',
        variable: ['data', 'invoices', '[]', 'id'],
        code: BAD_USER_INPUT,
        type: CANNOT_FIND_ALL_INVOICES,
        message: 'Cannot find all specified Invoices with ids {missingInvoiceIds}',
    },
    INVALID_REQUEST_MODE: {
        mutation: 'registerMultiPayment',
        code: BAD_USER_INPUT,
        type: INVALID_REQUEST_MODE,
        message: 'Cannot detect receipt or invoice request',
    },
    ACQUIRING_INTEGRATION_NOT_FOUND: {
        mutation: 'registerMultiPayment',
        variable: ['data'],
        code: BAD_USER_INPUT,
        type: NOT_FOUND,
        message: 'AcquiringIntegration not found',
    },
    CANNOT_FIND_ALL_BILLING_INTEGRATION: {
        mutation: 'registerMultiPayment',
        variable: ['data'],
        code: BAD_USER_INPUT,
        type: NOT_FOUND,
        message: 'Cannot find all BillingIntegration for specified receipts',
    },
}

module.exports = {
    REGISTER_MULTI_PAYMENT_ERRORS,
}
