const RENT_PAYMENT_METHOD_MOMO = 'momo'
const RENT_PAYMENT_METHOD_BANK_TRANSFER = 'bank_transfer'
const RENT_PAYMENT_METHOD_CASH = 'cash'
const RENT_PAYMENT_METHOD_CARD = 'card'

const RENT_PAYMENT_METHODS = [
    RENT_PAYMENT_METHOD_MOMO,
    RENT_PAYMENT_METHOD_BANK_TRANSFER,
    RENT_PAYMENT_METHOD_CASH,
    RENT_PAYMENT_METHOD_CARD,
]

const RENT_PAYMENT_PROVIDER_PAYSTACK = 'paystack'
const RENT_PAYMENT_PROVIDER_HUBTEL = 'hubtel'
const RENT_PAYMENT_PROVIDER_FLUTTERWAVE = 'flutterwave'
const RENT_PAYMENT_PROVIDER_MTN_MOMO = 'mtn_momo'
const RENT_PAYMENT_PROVIDER_MANUAL = 'manual'

const RENT_PAYMENT_PROVIDERS = [
    RENT_PAYMENT_PROVIDER_PAYSTACK,
    RENT_PAYMENT_PROVIDER_HUBTEL,
    RENT_PAYMENT_PROVIDER_FLUTTERWAVE,
    RENT_PAYMENT_PROVIDER_MTN_MOMO,
    RENT_PAYMENT_PROVIDER_MANUAL,
]

module.exports = {
    RENT_PAYMENT_METHOD_BANK_TRANSFER,
    RENT_PAYMENT_METHOD_CARD,
    RENT_PAYMENT_METHOD_CASH,
    RENT_PAYMENT_METHOD_MOMO,
    RENT_PAYMENT_METHODS,
    RENT_PAYMENT_PROVIDER_FLUTTERWAVE,
    RENT_PAYMENT_PROVIDER_HUBTEL,
    RENT_PAYMENT_PROVIDER_MANUAL,
    RENT_PAYMENT_PROVIDER_MTN_MOMO,
    RENT_PAYMENT_PROVIDER_PAYSTACK,
    RENT_PAYMENT_PROVIDERS,
}