const LEDGER_ENTRY_TYPE_CHARGE = 'charge'
const LEDGER_ENTRY_TYPE_PAYMENT = 'payment'
const LEDGER_ENTRY_TYPE_REVERSAL = 'reversal'
const LEDGER_ENTRY_TYPE_ADJUSTMENT = 'adjustment'
const LEDGER_ENTRY_TYPES = [
    LEDGER_ENTRY_TYPE_CHARGE,
    LEDGER_ENTRY_TYPE_PAYMENT,
    LEDGER_ENTRY_TYPE_REVERSAL,
    LEDGER_ENTRY_TYPE_ADJUSTMENT,
]

const LEDGER_ENTRY_DIRECTION_DEBIT = 'debit'
const LEDGER_ENTRY_DIRECTION_CREDIT = 'credit'
const LEDGER_ENTRY_DIRECTIONS = [
    LEDGER_ENTRY_DIRECTION_DEBIT,
    LEDGER_ENTRY_DIRECTION_CREDIT,
]

const LEDGER_ENTRY_STATUS_POSTED = 'posted'
const LEDGER_ENTRY_STATUSES = [LEDGER_ENTRY_STATUS_POSTED]

const TENANT_LEDGER_STATUS_ACTIVE = 'active'
const TENANT_LEDGER_STATUS_CLOSED = 'closed'
const TENANT_LEDGER_STATUSES = [TENANT_LEDGER_STATUS_ACTIVE, TENANT_LEDGER_STATUS_CLOSED]

module.exports = {
    LEDGER_ENTRY_DIRECTION_CREDIT,
    LEDGER_ENTRY_DIRECTION_DEBIT,
    LEDGER_ENTRY_DIRECTIONS,
    LEDGER_ENTRY_STATUS_POSTED,
    LEDGER_ENTRY_STATUSES,
    LEDGER_ENTRY_TYPE_ADJUSTMENT,
    LEDGER_ENTRY_TYPE_CHARGE,
    LEDGER_ENTRY_TYPE_PAYMENT,
    LEDGER_ENTRY_TYPE_REVERSAL,
    LEDGER_ENTRY_TYPES,
    TENANT_LEDGER_STATUS_ACTIVE,
    TENANT_LEDGER_STATUS_CLOSED,
    TENANT_LEDGER_STATUSES,
}