const ONLINE_INTERACTION_CHECK_ACCOUNT_SUCCESS_STATUS = 'FOUND'
const ONLINE_INTERACTION_CHECK_ACCOUNT_ERROR_STATUS = 'ERROR'
const ONLINE_INTERACTION_CHECK_ACCOUNT_NOT_FOUND_STATUS = 'NOT_FOUND'

module.exports = {
    ONLINE_INTERACTION_CHECK_ACCOUNT_SUCCESS_STATUS,
    ONLINE_INTERACTION_CHECK_ACCOUNT_ERROR_STATUS,
    ONLINE_INTERACTION_CHECK_ACCOUNT_NOT_FOUND_STATUS,
}