const BILLING_CYCLE_MONTHLY = 'monthly'
const BILLING_CYCLE_ANNUAL = 'annual'

const BILLING_CYCLES = [
    BILLING_CYCLE_MONTHLY,
    BILLING_CYCLE_ANNUAL,
]

const PARTIAL_MONTH_RULE_FULL = 'full'
const PARTIAL_MONTH_RULE_PRORATE_BY_DAYS = 'prorate_by_days'
const PARTIAL_MONTH_RULE_NONE = 'none'
const DEFAULT_RENT_CHARGE_CURRENCY_CODE = 'GHS'

const PARTIAL_MONTH_RULES = [
    PARTIAL_MONTH_RULE_FULL,
    PARTIAL_MONTH_RULE_PRORATE_BY_DAYS,
    PARTIAL_MONTH_RULE_NONE,
]

const RENT_CHARGE_STATUS_DRAFT = 'draft'
const RENT_CHARGE_STATUS_INVOICED = 'invoiced'
const RENT_CHARGE_STATUS_PARTIALLY_PAID = 'partially_paid'
const RENT_CHARGE_STATUS_PAID = 'paid'
const RENT_CHARGE_STATUS_CANCELED = 'canceled'

const RENT_CHARGE_STATUSES = [
    RENT_CHARGE_STATUS_DRAFT,
    RENT_CHARGE_STATUS_INVOICED,
    RENT_CHARGE_STATUS_PARTIALLY_PAID,
    RENT_CHARGE_STATUS_PAID,
    RENT_CHARGE_STATUS_CANCELED,
]

module.exports = {
    BILLING_CYCLE_MONTHLY,
    BILLING_CYCLE_ANNUAL,
    BILLING_CYCLES,
    PARTIAL_MONTH_RULE_FULL,
    PARTIAL_MONTH_RULE_PRORATE_BY_DAYS,
    PARTIAL_MONTH_RULE_NONE,
    PARTIAL_MONTH_RULES,
    DEFAULT_RENT_CHARGE_CURRENCY_CODE,
    RENT_CHARGE_STATUS_DRAFT,
    RENT_CHARGE_STATUS_INVOICED,
    RENT_CHARGE_STATUS_PARTIALLY_PAID,
    RENT_CHARGE_STATUS_PAID,
    RENT_CHARGE_STATUS_CANCELED,
    RENT_CHARGE_STATUSES,
}
