// Value of `User.type`, that indicates, that this user is a resident (from mobile client).
const RESIDENT = 'resident'
const STAFF = 'staff'
const SERVICE = 'service'
const USER_TYPES = [STAFF, RESIDENT, SERVICE]

const APPLE_ID_IDP_TYPE = 'apple_id'
const SBER_ID_IDP_TYPE = 'sber_id'
const SBBOL_IDP_TYPE = 'sbbol'
const TELEGRAM_IDP_TYPE = 'telegram'
const IDP_TYPES = [APPLE_ID_IDP_TYPE, SBER_ID_IDP_TYPE, SBBOL_IDP_TYPE, TELEGRAM_IDP_TYPE]

const MIN_PASSWORD_LENGTH = 8
const MAX_PASSWORD_LENGTH = 128
const MIN_COUNT_OF_DIFFERENT_CHARACTERS_IN_PASSWORD = 4
const LOCK_TIMEOUT = 1
const SMS_CODE_LENGTH = 4
const SMS_CODE_TTL = 60 // seconds
const CONFIRM_PHONE_ACTION_EXPIRY = 3600 // 1 hour
const CONFIRM_PHONE_SMS_MAX_RETRIES = 10
const MAX_SMS_FOR_IP_BY_DAY = 10
const MAX_SMS_FOR_PHONE_BY_DAY = 10
const MAX_REQUESTS_FOR_IP_PER_DAY = 10
const MAX_REQUESTS_FOR_PHONE_PER_DAY = 10
const MAX_REQUESTS_FOR_EMAIL_PER_DAY = 10
const MAX_REQUESTS_FOR_USER_PER_DAY = 10
const MAX_TOTAL_REQUESTS_FOR_USER = 50
const MAX_TOTAL_REQUESTS_FOR_EMAIL = 50
const MAX_TOTAL_REQUESTS_FOR_PHONE = 50

const SBER_ID_SESSION_KEY = 'sberid'
const APPLE_ID_SESSION_KEY = 'appleid'

const LOCALE_RU = 'ru'
const LOCALE_EN = 'en'
const LOCALE_ES = 'es'
const LOCALES = [LOCALE_RU, LOCALE_EN, LOCALE_ES]

module.exports = {
    MIN_PASSWORD_LENGTH,
    MAX_PASSWORD_LENGTH,
    LOCK_TIMEOUT,
    SMS_CODE_LENGTH,
    SMS_CODE_TTL,
    CONFIRM_PHONE_ACTION_EXPIRY,
    CONFIRM_PHONE_SMS_MAX_RETRIES,
    MAX_SMS_FOR_IP_BY_DAY,
    MAX_SMS_FOR_PHONE_BY_DAY,
    MAX_REQUESTS_FOR_IP_PER_DAY,
    MAX_REQUESTS_FOR_PHONE_PER_DAY,
    MAX_REQUESTS_FOR_USER_PER_DAY,
    MAX_REQUESTS_FOR_EMAIL_PER_DAY,
    MAX_TOTAL_REQUESTS_FOR_USER,
    MAX_TOTAL_REQUESTS_FOR_EMAIL,
    MAX_TOTAL_REQUESTS_FOR_PHONE,
    RESIDENT,
    STAFF,
    SERVICE,
    USER_TYPES,
    APPLE_ID_IDP_TYPE,
    SBER_ID_IDP_TYPE,
    SBBOL_IDP_TYPE,
    TELEGRAM_IDP_TYPE,
    IDP_TYPES,
    SBER_ID_SESSION_KEY,
    APPLE_ID_SESSION_KEY,
    LOCALE_EN,
    LOCALE_RU,
    LOCALES,
    MIN_COUNT_OF_DIFFERENT_CHARACTERS_IN_PASSWORD,
}
