const {
    EMAIL_VERIFY_CODE_MESSAGE_TYPE,
    VERIFY_USER_EMAIL_MESSAGE_TYPE,
} = require('@condo/domains/notification/constants/constants')


const EMAIL_CONFIRMATION_FLOWS = {
    CODE: 'CODE',
    LINK_FOR_STAFF_VERIFICATION: 'LINK_FOR_STAFF_VERIFICATION',
}

const MESSAGE_TYPE_BY_EMAIL_CONFIRMATION_FLOW = {
    [EMAIL_CONFIRMATION_FLOWS.CODE]: EMAIL_VERIFY_CODE_MESSAGE_TYPE,
    [EMAIL_CONFIRMATION_FLOWS.LINK_FOR_STAFF_VERIFICATION]: VERIFY_USER_EMAIL_MESSAGE_TYPE,
}

module.exports = {
    EMAIL_CONFIRMATION_FLOWS,
    MESSAGE_TYPE_BY_EMAIL_CONFIRMATION_FLOW,
}
