const AUTH_COUNTER_LIMIT_TYPE = 'auth'
const FIND_ORGANIZATION_BY_TIN_TYPE = 'findOrganizationsByTin'
const RATE_LIMIT_TYPE = 'rateLimit'
const LOGIN_BY_PHONE_AND_PASSWORD_LIMIT_TYPE = 'loginByPhoneAndPassword'

module.exports = {
    AUTH_COUNTER_LIMIT_TYPE,
    FIND_ORGANIZATION_BY_TIN_TYPE,
    RATE_LIMIT_TYPE,
    LOGIN_BY_PHONE_AND_PASSWORD_LIMIT_TYPE,
}
