const SMS_COUNTER_LIMIT_TYPE = 'sms'
const EMAIL_COUNTER_LIMIT_TYPE = 'email'
const FIND_ORGANIZATION_BY_TIN_TYPE = 'findOrganizationsByTin'
const RATE_LIMIT_TYPE = 'rateLimit'
const AUTH_COUNTER_LIMIT_TYPE = 'auth'
const CHECK_USER_EXISTENCE_TYPE = 'checkUserExistence'
const CHANGE_USER_PASSWORD_TYPE = 'changeUserPassword'
const CHANGE_OR_VERIFY_USER_EMAIL_TYPE = 'changeOrVerifyUserEmail'
const CHANGE_TWO_FACTOR_AUTHENTICATION_TYPE = 'ChangeTwoFactorAuthentication'

module.exports = {
    SMS_COUNTER_LIMIT_TYPE,
    EMAIL_COUNTER_LIMIT_TYPE,
    FIND_ORGANIZATION_BY_TIN_TYPE,
    RATE_LIMIT_TYPE,
    AUTH_COUNTER_LIMIT_TYPE,
    CHECK_USER_EXISTENCE_TYPE,
    CHANGE_USER_PASSWORD_TYPE,
    CHANGE_OR_VERIFY_USER_EMAIL_TYPE,
    CHANGE_TWO_FACTOR_AUTHENTICATION_TYPE,
}
