const USER_EXTERNAL_IDENTITY_AUTH_PATH = '/api/:type/auth'
const USER_EXTERNAL_IDENTITY_AUTH_CALLBACK_PATH = '/api/:type/auth/callback'
const USER_EXTERNAL_IDENTITY_AUTH_SESSION_KEY = 'user_external_identity'

module.exports = {
    USER_EXTERNAL_IDENTITY_AUTH_PATH,
    USER_EXTERNAL_IDENTITY_AUTH_CALLBACK_PATH,
    USER_EXTERNAL_IDENTITY_AUTH_SESSION_KEY,
}
