const OVERLAPPING_ERROR = '[overlapping]'

const WRONG_PAYMENT_STATUS_TRANSITION_ERROR = '[status:wrongTransition]'

const SBBOL_OFFER_ACCEPT_IS_NULL_ERROR = '[sbbolOfferAccept:isNull]'

const SBBOL_OFFER_ACCEPT_HAS_INCORRECT_PAYER_REQUISITES_ERROR = '[sbbolOfferAccept:hasIncorrectPayerRequisites]'

module.exports = {
    OVERLAPPING_ERROR,
    WRONG_PAYMENT_STATUS_TRANSITION_ERROR,
    SBBOL_OFFER_ACCEPT_IS_NULL_ERROR,
    SBBOL_OFFER_ACCEPT_HAS_INCORRECT_PAYER_REQUISITES_ERROR,
}
