const SUBSCRIPTION_PERIOD = {
    MONTH: 'month',
    YEAR: 'year',
}
const SUBSCRIPTION_PERIODS = Object.values(SUBSCRIPTION_PERIOD)

const PERIOD_TO_MONTHS = {
    [SUBSCRIPTION_PERIOD.MONTH]: 1,
    [SUBSCRIPTION_PERIOD.YEAR]: 12,
}

const SUBSCRIPTION_CONTEXT_CREATED_STATUS = 'CREATED'
const SUBSCRIPTION_CONTEXT_DONE_STATUS = 'DONE'
const SUBSCRIPTION_CONTEXT_PENDING_STATUS = 'PENDING'
const SUBSCRIPTION_CONTEXT_ERROR_STATUS = 'ERROR'

const SUBSCRIPTION_CONTEXT_STATUS = {
    [SUBSCRIPTION_CONTEXT_CREATED_STATUS]: SUBSCRIPTION_CONTEXT_CREATED_STATUS,
    [SUBSCRIPTION_CONTEXT_DONE_STATUS]: SUBSCRIPTION_CONTEXT_DONE_STATUS,
    [SUBSCRIPTION_CONTEXT_PENDING_STATUS]: SUBSCRIPTION_CONTEXT_PENDING_STATUS,
    [SUBSCRIPTION_CONTEXT_ERROR_STATUS]: SUBSCRIPTION_CONTEXT_ERROR_STATUS,
}

const SUBSCRIPTION_CONTEXT_STATUS_TRANSITIONS = {
    [SUBSCRIPTION_CONTEXT_CREATED_STATUS]: [SUBSCRIPTION_CONTEXT_PENDING_STATUS, SUBSCRIPTION_CONTEXT_ERROR_STATUS, SUBSCRIPTION_CONTEXT_DONE_STATUS],
    [SUBSCRIPTION_CONTEXT_DONE_STATUS]: [],
    [SUBSCRIPTION_CONTEXT_PENDING_STATUS]: [SUBSCRIPTION_CONTEXT_ERROR_STATUS, SUBSCRIPTION_CONTEXT_DONE_STATUS],
    [SUBSCRIPTION_CONTEXT_ERROR_STATUS]: [],
}
const SUBSCRIPTION_CONTEXT_STATUSES = Object.values(SUBSCRIPTION_CONTEXT_STATUS)

const SUBSCRIPTION_PAYMENT_BUFFER_DAYS = 5

const SUBSCRIPTION_PLAN_TYPE_SERVICE = 'service'
const SUBSCRIPTION_PLAN_TYPE_FEATURE = 'feature'
const SUBSCRIPTION_PLAN_TYPES = [SUBSCRIPTION_PLAN_TYPE_SERVICE, SUBSCRIPTION_PLAN_TYPE_FEATURE]

const planFeatureField = (name) => ({
    schemaDoc: `Whether ${name} feature is included in this plan`,
    type: 'Checkbox',
    defaultValue: false,
    isRequired: true,
})

const SUBSCRIPTION_PLAN_FEATURE_FIELDS = {
    payments: planFeatureField('payments'),
    meters: planFeatureField('meters'),
    tickets: planFeatureField('tickets'),
    news: planFeatureField('news'),
    marketplace: planFeatureField('marketplace'),
    support: planFeatureField('support'),
    ai: planFeatureField('ai'),
    customization: planFeatureField('customization'),
    properties: planFeatureField('properties'),
    analytics: planFeatureField('analytics'),
}

const SUBSCRIPTION_PLAN_FEATURES = Object.keys(SUBSCRIPTION_PLAN_FEATURE_FIELDS)

module.exports = {
    SUBSCRIPTION_PERIOD,
    SUBSCRIPTION_PERIODS,
    PERIOD_TO_MONTHS,
    SUBSCRIPTION_CONTEXT_STATUS,
    SUBSCRIPTION_CONTEXT_STATUSES,
    SUBSCRIPTION_PAYMENT_BUFFER_DAYS,
    SUBSCRIPTION_CONTEXT_STATUS_TRANSITIONS,
    SUBSCRIPTION_PLAN_TYPE_SERVICE,
    SUBSCRIPTION_PLAN_TYPE_FEATURE,
    SUBSCRIPTION_PLAN_TYPES,
    SUBSCRIPTION_PLAN_FEATURE_FIELDS,
    SUBSCRIPTION_PLAN_FEATURES,
}