const SUBSCRIPTION_PERIOD = {
    MONTH: 'month',
    YEAR: 'year',
}
const SUBSCRIPTION_PERIODS = Object.values(SUBSCRIPTION_PERIOD)

const PERIOD_TO_MONTHS = {
    [SUBSCRIPTION_PERIOD.MONTH]: 1,
    [SUBSCRIPTION_PERIOD.YEAR]: 12,
}

const SUBSCRIPTION_CONTEXT_STATUS = {
    CREATED: 'CREATED',
    DONE: 'DONE',
    ERROR: 'ERROR',
}
const SUBSCRIPTION_CONTEXT_STATUSES = Object.values(SUBSCRIPTION_CONTEXT_STATUS)

const SUBSCRIPTION_PAYMENT_BUFFER_DAYS = 5

module.exports = {
    SUBSCRIPTION_PERIOD,
    SUBSCRIPTION_PERIODS,
    PERIOD_TO_MONTHS,
    SUBSCRIPTION_CONTEXT_STATUS,
    SUBSCRIPTION_CONTEXT_STATUSES,
    SUBSCRIPTION_PAYMENT_BUFFER_DAYS,
}