/**
 * This file is autogenerated by `createservice miniapp.AllOrganizationAppsService --type queries`
 * In most cases you should not change it by hands. And please don't remove `AUTOGENERATE MARKER`s
 */

const { AllMiniAppsService } = require('./AllMiniAppsService')
const { B2BApp } = require('./B2BApp')
const { B2BAppContext } = require('./B2BAppContext')
const { B2BAppAccessRight } = require('./B2BAppAccessRight')
const { B2CApp } = require('./B2CApp')
const { B2CAppAccessRight } = require('./B2CAppAccessRight')
const { B2CAppBuild } = require('./B2CAppBuild')
const { B2CAppProperty } = require('./B2CAppProperty')
/* AUTOGENERATE MARKER <REQUIRE> */

module.exports = {
    AllMiniAppsService,
    B2BApp,
    B2BAppContext,
    B2BAppAccessRight,
    B2CApp,
    B2CAppAccessRight,
    B2CAppBuild,
    B2CAppProperty,
/* AUTOGENERATE MARKER <EXPORTS> */
}
