const FEEDBACK_VALUES_BY_KEY = {
    BAD: 'bad',
    GOOD: 'good',
    RETURNED: 'returned',
}

const FEEDBACK_VALUES = Object.values(FEEDBACK_VALUES_BY_KEY)

const FEEDBACK_ADDITIONAL_OPTIONS_BY_KEY = {
    LOW_QUALITY: 'lowQuality',
    HIGH_QUALITY: 'highQuality',
    SLOWLY: 'slowly',
    QUICKLY: 'quickly',
}

const FEEDBACK_ADDITIONAL_OPTIONS = Object.values(FEEDBACK_ADDITIONAL_OPTIONS_BY_KEY)

const FEEDBACK_BAD_OPTIONS = [
    FEEDBACK_ADDITIONAL_OPTIONS_BY_KEY.LOW_QUALITY,
    FEEDBACK_ADDITIONAL_OPTIONS_BY_KEY.SLOWLY,
]

const FEEDBACK_GOOD_OPTIONS = [
    FEEDBACK_ADDITIONAL_OPTIONS_BY_KEY.HIGH_QUALITY,
    FEEDBACK_ADDITIONAL_OPTIONS_BY_KEY.QUICKLY,
]

module.exports = {
    FEEDBACK_VALUES_BY_KEY,
    FEEDBACK_VALUES,
    FEEDBACK_ADDITIONAL_OPTIONS_BY_KEY,
    FEEDBACK_ADDITIONAL_OPTIONS,
    FEEDBACK_BAD_OPTIONS,
    FEEDBACK_GOOD_OPTIONS,
}