const INCIDENT_STATUS_ACTUAL = 'actual'
const INCIDENT_STATUS_NOT_ACTUAL = 'not_actual'
const INCIDENT_STATUSES = [
    INCIDENT_STATUS_ACTUAL,
    INCIDENT_STATUS_NOT_ACTUAL,
]
const INCIDENT_WORK_TYPE_SCHEDULED = 'scheduled'
const INCIDENT_WORK_TYPE_EMERGENCY = 'emergency'
const INCIDENT_WORK_TYPES = [
    INCIDENT_WORK_TYPE_SCHEDULED,
    INCIDENT_WORK_TYPE_EMERGENCY,
]

const INCIDENT_STATUS_COLORS = {
    [INCIDENT_STATUS_ACTUAL]: {
        text: '#ffffff',
        background: '#EB3468',
    },
    [INCIDENT_STATUS_NOT_ACTUAL]: {
        text: '#ffffff',
        background: '#39CE66',
    },
}

const INCIDENT_CATEGORY_IDS = {
    WATER: '4509f01b-3f9b-4a07-83ea-3b548c492146',
}
const INCIDENT_PROBLEM_IDS = {
    NO_HOT_AND_COLD_WATER: '79af87cc-9b17-4f0e-a527-2f61beffd5e1',
    NOT_HOT_WATER: '5289e8aa-e5f9-4dc5-8540-49f6e0b2a004',
    NO_COLD_WATER: '96f91218-1e03-4258-9883-64cf0753ac45',
}

module.exports = {
    INCIDENT_STATUS_ACTUAL,
    INCIDENT_STATUS_NOT_ACTUAL,
    INCIDENT_STATUSES,
    INCIDENT_STATUS_COLORS,
    INCIDENT_WORK_TYPE_SCHEDULED,
    INCIDENT_WORK_TYPE_EMERGENCY,
    INCIDENT_WORK_TYPES,
    INCIDENT_CATEGORY_IDS,
    INCIDENT_PROBLEM_IDS,
}
