const MAX_DESCRIPTION_DISPLAY_LENGTH = 150
const TICKET_CHART_PAGE_SIZE = 6
const MAX_CHART_NAME_LENGTH = 35
const MAX_CHART_LEGEND_ELEMENTS = 3

export {
    MAX_DESCRIPTION_DISPLAY_LENGTH,
    TICKET_CHART_PAGE_SIZE,
    MAX_CHART_NAME_LENGTH,
    MAX_CHART_LEGEND_ELEMENTS,
}
