const EMPTY_VALID_BEFORE_DATE = 'EMPTY_VALID_BEFORE_DATE'
const NEWS_ITEM_ALREADY_READ = 'NEWS_ITEM_ALREADY_READ'
const EDIT_DENIED_ALREADY_SENT = 'EDIT_DENIED_ALREADY_SENT'
const VALIDITY_DATE_LESS_THAN_SEND_DATE = 'VALIDITY_DATE_LESS_THAN_SEND_DATE'

module.exports = {
    EMPTY_VALID_BEFORE_DATE,
    NEWS_ITEM_ALREADY_READ,
    EDIT_DENIED_ALREADY_SENT,
    VALIDITY_DATE_LESS_THAN_SEND_DATE,
}
