const EMPTY_VALID_BEFORE_DATE = 'EMPTY_VALID_BEFORE_DATE'
const NEWS_ITEM_ALREADY_READ = 'NEWS_ITEM_ALREADY_READ'
const VALIDITY_DATE_LESS_THAN_SEND_DATE = 'VALIDITY_DATE_LESS_THAN_SEND_DATE'
const EDIT_DENIED_ALREADY_SENT = 'EDIT_DENIED_ALREADY_SENT'
const EDIT_DENIED_PUBLISHED = 'EDIT_DENIED_PUBLISHED'
const PROFANITY_TITLE_DETECTED_MOT_ERF_KER = 'PROFANITY_TITLE_DETECTED_MOT_ERF_KER'
const PROFANITY_BODY_DETECTED_MOT_ERF_KER = 'PROFANITY_BODY_DETECTED_MOT_ERF_KER'
const WRONG_SEND_DATE = 'WRONG_SEND_DATE'
const NO_NEWS_ITEM_SCOPES = 'NO_NEWS_ITEM_SCOPES'

const BAD_STATUS_TRANSITION = 'BAD_STATUS_TRANSITION'
const NOT_NEWS_SHARING_CONTEXT = 'NOT_NEWS_SHARING_CONTEXT'
const CANT_CHANGE_PUBLISHED_NEWS_ITEM_SHARINGS = 'CANT_CHANGE_PUBLISHED_NEWS_ITEM_SHARINGS'

const BAD_RECIPIENTS_JSON = 'BAD_RECIPIENTS_JSON'
const BAD_RECIPIENTS_COUNT_JSON = 'BAD_RECIPIENTS_COUNT_JSON'
const BAD_PREVIEW_JSON = 'BAD_PREVIEW_JSON'
const BAD_NEWS_INFO_JSON = 'BAD_NEWS_INFO_JSON'
const BAD_SHARING_PARAMS_JSON = 'BAD_SHARING_PARAMS_JSON'

module.exports = {
    EMPTY_VALID_BEFORE_DATE,
    NEWS_ITEM_ALREADY_READ,
    VALIDITY_DATE_LESS_THAN_SEND_DATE,
    EDIT_DENIED_ALREADY_SENT,
    EDIT_DENIED_PUBLISHED,
    PROFANITY_TITLE_DETECTED_MOT_ERF_KER,
    PROFANITY_BODY_DETECTED_MOT_ERF_KER,
    WRONG_SEND_DATE,
    NO_NEWS_ITEM_SCOPES,
    BAD_STATUS_TRANSITION,
    NOT_NEWS_SHARING_CONTEXT,
    CANT_CHANGE_PUBLISHED_NEWS_ITEM_SHARINGS,
    BAD_RECIPIENTS_JSON,
    BAD_RECIPIENTS_COUNT_JSON,
    BAD_NEWS_INFO_JSON,
    BAD_PREVIEW_JSON,
    BAD_SHARING_PARAMS_JSON,
}
