const EMPTY_VALID_BEFORE_DATE = 'EMPTY_VALID_BEFORE_DATE'
const NEWS_ITEM_ALREADY_READ = 'NEWS_ITEM_ALREADY_READ'
const VALIDITY_DATE_LESS_THAN_SEND_DATE = 'VALIDITY_DATE_LESS_THAN_SEND_DATE'
const EDIT_DENIED_ALREADY_SENT = 'EDIT_DENIED_ALREADY_SENT'
const EDIT_DENIED_PUBLISHED = 'EDIT_DENIED_PUBLISHED'
const PROFANITY_DETECTED_MOT_ERF_KER = 'PROFANITY_DETECTED_MOT_ERF_KER'
const WRONG_MESSAGE_TRANSPORT = 'WRONG_MESSAGE_TRANSPORT'
const WRONG_MESSAGE_TYPE = 'WRONG_MESSAGE_TYPE'
const NO_NEED_TO_ENABLE_NOTIFICATIONS = 'NO_NEED_TO_ENABLE_NOTIFICATIONS'

module.exports = {
    EMPTY_VALID_BEFORE_DATE,
    NEWS_ITEM_ALREADY_READ,
    VALIDITY_DATE_LESS_THAN_SEND_DATE,
    EDIT_DENIED_ALREADY_SENT,
    EDIT_DENIED_PUBLISHED,
    PROFANITY_DETECTED_MOT_ERF_KER,
    WRONG_MESSAGE_TRANSPORT,
    WRONG_MESSAGE_TYPE,
    NO_NEED_TO_ENABLE_NOTIFICATIONS,
}
