const NEWS_ITEM_SCOPE_TYPE_UNKNOWN = 'unknown'
const NEWS_ITEM_SCOPE_TYPE_ORGANIZATION = 'organization'
const NEWS_ITEM_SCOPE_TYPE_PROPERTY = 'property'
const NEWS_ITEM_SCOPE_TYPE_PROPERTY_UNIT_TYPE = 'property_unitType'
const NEWS_ITEM_SCOPE_TYPE_PROPERTY_UNIT_TYPE_UNIT_NAME = 'property_unitType_unitName'

const NEWS_ITEMS_SCOPES_TYPES = [
    NEWS_ITEM_SCOPE_TYPE_UNKNOWN,
    NEWS_ITEM_SCOPE_TYPE_ORGANIZATION,
    NEWS_ITEM_SCOPE_TYPE_PROPERTY,
    NEWS_ITEM_SCOPE_TYPE_PROPERTY_UNIT_TYPE,
    NEWS_ITEM_SCOPE_TYPE_PROPERTY_UNIT_TYPE_UNIT_NAME,
]

module.exports = {
    NEWS_ITEMS_SCOPES_TYPES,
    NEWS_ITEM_SCOPE_TYPE_UNKNOWN,
    NEWS_ITEM_SCOPE_TYPE_ORGANIZATION,
    NEWS_ITEM_SCOPE_TYPE_PROPERTY,
    NEWS_ITEM_SCOPE_TYPE_PROPERTY_UNIT_TYPE,
    NEWS_ITEM_SCOPE_TYPE_PROPERTY_UNIT_TYPE_UNIT_NAME,
}
