const INVALID_MIMETYPE = 'INVALID_MIMETYPE'
const MULTIPLE_FOUND = 'MULTIPLE_FOUND'
const SHARED_ID_CONSTRAINT = 'SHARED_ID_CONSTRAINT'

module.exports = {
    INVALID_MIMETYPE,
    MULTIPLE_FOUND,
    SHARED_ID_CONSTRAINT,
}