/**
 * Generated by `createschema miniapp.B2CAppProperty 'app:Relationship:B2CApp:PROTECT; address:Text;' --force`
 */

import {
    B2CAppProperty,
    B2CAppPropertyCreateInput,
    B2CAppPropertyUpdateInput,
    QueryAllB2CAppPropertiesArgs,
} from '@app/condo/schema'
import { generateNewReactHooks } from '@condo/domains/common/utils/codegeneration/generate.hooks'
import { B2CAppProperty as B2CAppPropertyGQL } from '@condo/domains/miniapp/gql'

const {
    useObject,
    useObjects,
    useCreate,
    useUpdate,
    useSoftDelete,
} = generateNewReactHooks<B2CAppProperty, B2CAppPropertyCreateInput, B2CAppPropertyUpdateInput, QueryAllB2CAppPropertiesArgs>(B2CAppPropertyGQL)

export {
    useObject,
    useObjects,
    useCreate,
    useUpdate,
    useSoftDelete,
}
