const PROCESSING = 'processing'
const COMPLETED = 'completed'
const ERROR = 'error'
const CANCELLED = 'cancelled'

const EXPORT_STATUS_VALUES = [PROCESSING, COMPLETED, ERROR, CANCELLED]

const EXCEL = 'excel'

const EXPORT_FORMAT_VALUES = [EXCEL]

const EXPORT_PROCESSING_BATCH_SIZE = 100

module.exports = {
    PROCESSING,
    COMPLETED,
    ERROR,
    CANCELLED,
    EXCEL,
    EXPORT_STATUS_VALUES,
    EXPORT_FORMAT_VALUES,
    EXPORT_PROCESSING_BATCH_SIZE,
}
