const PROCESSING = 'processing'
const COMPLETED = 'completed'
const ERROR = 'error'

const EXPORT_STATUS_VALUES = [PROCESSING, COMPLETED, ERROR]

const EXCEL = 'excel'

const EXPORT_FORMAT_VALUES = [EXCEL]

const EXPORT_PROCESSING_BATCH_SIZE = 1000

module.exports = {
    PROCESSING,
    COMPLETED,
    ERROR,
    EXCEL,
    EXPORT_STATUS_VALUES,
    EXPORT_FORMAT_VALUES,
    EXPORT_PROCESSING_BATCH_SIZE,
}