const SETTINGS_TAB_SUBSCRIPTION = 'subscription'
const SETTINGS_TAB_EMPLOYEE_ROLES = 'employeeRoles'
const SETTINGS_TAB_PAYMENT_DETAILS = 'paymentDetails'
const SETTINGS_TAB_CONTACT_ROLES = 'contactRoles'
const SETTINGS_TAB_TICKET_ORGANIZATION = 'ticketOrganization'
const SETTINGS_TAB_CONTROL_ROOM = 'controlRoom'
const SETTINGS_TAB_MOBILE_FEATURE_CONFIG = 'mobileFeatureConfig'

module.exports = {
    SETTINGS_TAB_SUBSCRIPTION,
    SETTINGS_TAB_CONTACT_ROLES,
    SETTINGS_TAB_PAYMENT_DETAILS,
    SETTINGS_TAB_TICKET_ORGANIZATION,
    SETTINGS_TAB_CONTROL_ROOM,
    SETTINGS_TAB_EMPLOYEE_ROLES,
    SETTINGS_TAB_MOBILE_FEATURE_CONFIG,
}
