const SETTINGS_TAB_SUBSCRIPTION = 'subscription'
const SETTINGS_TAB_PROPERTY_HINT = 'hint'
const SETTINGS_TAB_PAYMENT_DETAILS = 'paymentDetails'
const SETTINGS_TAB_CONTACT_ROLES = 'contactRoles'
const SETTINGS_TAB_TICKET_ORGANIZATION = 'ticketOrganization'
const SETTINGS_TAB_CALL_CENTER = 'callCenter'

module.exports = {
    SETTINGS_TAB_SUBSCRIPTION,
    SETTINGS_TAB_PROPERTY_HINT,
    SETTINGS_TAB_CONTACT_ROLES,
    SETTINGS_TAB_PAYMENT_DETAILS,
    SETTINGS_TAB_TICKET_ORGANIZATION,
    SETTINGS_TAB_CALL_CENTER,
}
