const WEBHOOK_EVENT_PAYMENT_STATUS_UPDATED = 'payment.status.updated'

const WEBHOOK_EVENTS = [
    WEBHOOK_EVENT_PAYMENT_STATUS_UPDATED,
]

module.exports = {
    WEBHOOK_EVENT_PAYMENT_STATUS_UPDATED,
    WEBHOOK_EVENTS,
}
