const WEBHOOK_EVENT_PAYMENT_STATUS_UPDATED = 'payment.status.updated'
const WEBHOOK_EVENT_SUBSCRIPTION_ACTIVATED = 'subscription.activated'

const WEBHOOK_EVENTS = [
    WEBHOOK_EVENT_PAYMENT_STATUS_UPDATED,
    WEBHOOK_EVENT_SUBSCRIPTION_ACTIVATED,
]

module.exports = {
    WEBHOOK_EVENT_PAYMENT_STATUS_UPDATED,
    WEBHOOK_EVENT_SUBSCRIPTION_ACTIVATED,
    WEBHOOK_EVENTS,
}
