const WORKER_FINGERPRINT = 'worker'

const WORKER_TASK_PROCESSING = 'processing'
const WORKER_TASK_COMPLETED = 'completed'
const WORKER_TASK_ERROR = 'error'

const TASK_STATUS_REFRESH_POLL_INTERVAL = 2000

module.exports = {
    WORKER_FINGERPRINT,
    WORKER_TASK_PROCESSING,
    WORKER_TASK_COMPLETED,
    WORKER_TASK_ERROR,
    TASK_STATUS_REFRESH_POLL_INTERVAL,
}