/**
 * Generated by `createservice miniapp.GetOIDCClientService '--type=queries'`
 */

const { makeClient } = require('@open-condo/keystone/test.utils')
const { expectToThrowAccessDeniedErrorToResult, expectToThrowAuthenticationErrorToResult } = require('@open-condo/keystone/test.utils')

const {
    getOIDCClientByTestClient,
    createTestB2CApp,
    createTestB2BApp,
    createOIDCClientByTestClient,
} = require('@dev-portal-api/domains/miniapp/utils/testSchema')
const {
    makeLoggedInAdminClient,
    makeLoggedInSupportClient,
    makeRegisteredAndLoggedInUser,
} = require('@dev-portal-api/domains/user/utils/testSchema')
 
describe('GetOIDCClientService', () => {
    let admin
    let support
    let b2cUser
    let b2cApp
    let b2bUser
    let b2bApp
    let anonymous
    let b2cOIDCClient
    let b2bOIDCClient
    beforeAll(async () => {
        admin = await makeLoggedInAdminClient()
        support = await makeLoggedInSupportClient()
        b2cUser = await makeRegisteredAndLoggedInUser()
        b2bUser = await makeRegisteredAndLoggedInUser()
        anonymous = await makeClient();

        [b2cApp] = await createTestB2CApp(b2cUser);
        [b2cOIDCClient] = await createOIDCClientByTestClient(b2cUser, b2cApp);

        [b2bApp] = await createTestB2BApp(b2bUser);
        [b2bOIDCClient] = await createOIDCClientByTestClient(b2bUser, b2bApp)
    })
    describe('Access tests', () => {
        test('Admin can get OIDC client of any app', async () => {
            const [readClient] = await getOIDCClientByTestClient(admin, b2cApp)
            expect(readClient).toHaveProperty('id', b2cOIDCClient.id)
            expect(readClient).toHaveProperty('clientId', b2cOIDCClient.clientId)
            expect(readClient).toHaveProperty('redirectUri', b2cOIDCClient.redirectUri)
        })
        test('Support can get OIDC client of any app', async () => {
            const [readClient] = await getOIDCClientByTestClient(support, b2bApp)
            expect(readClient).toHaveProperty('id', b2bOIDCClient.id)
            expect(readClient).toHaveProperty('clientId', b2bOIDCClient.clientId)
            expect(readClient).toHaveProperty('redirectUri', b2bOIDCClient.redirectUri)
        })
        describe('User', () => {
            describe('Can get OIDC client of app he created',  () => {
                test('For B2BApp', async () => {
                    const [readClient] = await getOIDCClientByTestClient(b2bUser, b2bApp)
                    expect(readClient).toHaveProperty('id', b2bOIDCClient.id)
                    expect(readClient).toHaveProperty('clientId', b2bOIDCClient.clientId)
                    expect(readClient).toHaveProperty('redirectUri', b2bOIDCClient.redirectUri)
                })
                test('For B2CApp', async () => {
                    const [readClient] = await getOIDCClientByTestClient(b2cUser, b2cApp)
                    expect(readClient).toHaveProperty('id', b2cOIDCClient.id)
                    expect(readClient).toHaveProperty('clientId', b2cOIDCClient.clientId)
                    expect(readClient).toHaveProperty('redirectUri', b2cOIDCClient.redirectUri)
                })
            })
            test('Cannot for other apps', async () => {
                await expectToThrowAccessDeniedErrorToResult(async () => {
                    await getOIDCClientByTestClient(b2bUser, b2cApp)
                })
                await expectToThrowAccessDeniedErrorToResult(async () => {
                    await getOIDCClientByTestClient(b2cUser, b2bApp)
                })
            })
        })
        test('Anonymous cannot get any OIDC client', async () => {
            await expectToThrowAuthenticationErrorToResult(async () => {
                await getOIDCClientByTestClient(anonymous, b2cApp)
            })
        })
    })
    describe('Logic tests', () => {
        test('Must not contain extra fields such as clientSecret', async () => {
            const [readClient] = await getOIDCClientByTestClient(b2cUser, b2cApp)
            expect(readClient).toEqual({
                id: b2cOIDCClient.id,
                clientId: b2cOIDCClient.clientId,
                redirectUri: b2cOIDCClient.redirectUri,
            })
        })
    })
})