/**
 * Generated by `createschema ticket.ExportTicketTask 'status:Select:processing,completed,error; format:Select:excel; exportedRecordsCount:Integer; totalRecordsCount:Integer; file?:File; meta?:Json'`
 */

const { Text, Relationship, Integer, Select, Checkbox, DateTimeUtc, CalendarDay, Decimal, Password, File, Url } = require('@keystonejs/fields')
const { Json } = require('@core/keystone/fields')
const { GQLListSchema } = require('@core/keystone/schema')
const { historical, versioned, uuided, tracked, softDeleted } = require('@core/keystone/plugins')
const { dvAndSender } = require('@condo/domains/common/schema/plugins/dvAndSender')
const access = require('@condo/domains/ticket/access/ExportTicketTask')


const ExportTicketTask = new GQLListSchema('ExportTicketTask', {
    // TODO(codegen): write doc for the ExportTicketTask domain model!
    schemaDoc: 'TODO DOC!',
    fields: {

        status: {
            // TODO(codegen): write doc for ExportTicketTask.status field!
            schemaDoc: 'TODO DOC!',
            type: Select,
            options: 'processing,completed,error',
            isRequired: true,
        },

        format: {
            // TODO(codegen): write doc for ExportTicketTask.format field!
            schemaDoc: 'TODO DOC!',
            type: Select,
            options: 'excel',
            isRequired: true,
        },

        exportedRecordsCount: {
            // TODO(codegen): write doc for ExportTicketTask.exportedRecordsCount field!
            schemaDoc: 'TODO DOC!',
            type: Integer,
            isRequired: true,
        },

        totalRecordsCount: {
            // TODO(codegen): write doc for ExportTicketTask.totalRecordsCount field!
            schemaDoc: 'TODO DOC!',
            type: Integer,
            isRequired: true,
        },

        file: {
            // TODO(codegen): write doc for ExportTicketTask.file field!
            schemaDoc: 'TODO DOC!',
            type: File,
        },

        meta: {
            // TODO(codegen): write doc for ExportTicketTask.meta field!
            schemaDoc: 'TODO DOC!',
            type: Json,
        },

    },
    plugins: [uuided(), versioned(), tracked(), softDeleted(), dvAndSender(), historical()],
    access: {
        read: access.canReadExportTicketTasks,
        create: access.canManageExportTicketTasks,
        update: access.canManageExportTicketTasks,
        delete: false,
        auth: true,
    },
})

module.exports = {
    ExportTicketTask,
}
