/**
 * Generated by `createschema ticket.TicketFilterTemplate 'name:Text; employee:Relationship:OrganizationEmployee:CASCADE; filters:Json'`
 */

const { Text, Relationship } = require('@keystonejs/fields')
const { GQLListSchema } = require('@core/keystone/schema')
const { historical, versioned, uuided, tracked, softDeleted } = require('@core/keystone/plugins')

const access = require('@condo/domains/ticket/access/TicketFilterTemplate')

const { TICKET_FILTER_FIELD } = require('./fields/TicketFilter')
const { dvAndSender } = require('../../common/schema/plugins/dvAndSender')


const TicketFilterTemplate = new GQLListSchema('TicketFilterTemplate', {
    schemaDoc: 'Employee specific ticket filter template',
    fields: {
        name: {
            schemaDoc: 'Ticket filter template name',
            type: Text,
            isRequired: true,
        },

        employee: {
            schemaDoc: 'Link to employee, who created this template',
            type: Relationship,
            ref: 'OrganizationEmployee',
            isRequired: true,
            knexOptions: { isNotNullable: true },
            kmigratorOptions: { null: false, on_delete: 'models.CASCADE' },
        },

        fields: TICKET_FILTER_FIELD,
    },
    plugins: [uuided(), versioned(), tracked(), softDeleted(), dvAndSender(), historical()],
    access: {
        read: access.canReadTicketFilterTemplates,
        create: access.canManageTicketFilterTemplates,
        update: access.canManageTicketFilterTemplates,
        delete: false,
        auth: true,
    },
})

module.exports = {
    TicketFilterTemplate,
}
