/**
 * Generated by `createschema ticket.TicketObserver 'ticket:Relationship:Ticket:CASCADE; user:Relationship:User:CASCADE'`
 */

const { historical, versioned, uuided, tracked, softDeleted, dvAndSender } = require('@open-condo/keystone/plugins')
const { GQLListSchema } = require('@open-condo/keystone/schema')

const access = require('@condo/domains/ticket/access/TicketObserver')


const TicketObserver = new GQLListSchema('TicketObserver', {
    schemaDoc: 'Employee/user who will be notified about the ticket',
    fields: {

        ticket: {
            schemaDoc: 'Link to ticket',
            type: 'Relationship',
            ref: 'Ticket.observers',
            isRequired: true,
            knexOptions: { isNotNullable: true }, // Required relationship only!
            kmigratorOptions: { null: false, on_delete: 'models.CASCADE' },
        },

        user: {
            schemaDoc: 'Link to employee/user',
            type: 'Relationship',
            ref: 'User',
            isRequired: true,
            knexOptions: { isNotNullable: true }, // Required relationship only!
            kmigratorOptions: { null: false, on_delete: 'models.CASCADE' },
        },

    },
    hooks: {
        afterChange: () => {
            // 1. When do I need to create a TicketChange and when not?
        },
    },
    kmigratorOptions: {
        constraints: [
            {
                type: 'models.UniqueConstraint',
                fields: ['ticket', 'user'],
                condition: 'Q(deletedAt__isnull=True)',
                name: 'ticket_observer_unique_ticket_and_user',
            },
        ],
    },
    plugins: [uuided(), versioned(), tracked(), softDeleted(), dvAndSender(), historical()],
    access: {
        read: access.canReadTicketObservers,
        create: access.canManageTicketObservers,
        update: access.canManageTicketObservers,
        delete: false,
        auth: true,
    },
})

module.exports = {
    TicketObserver,
}
