/**
 * Generated by `createschema ticket.TicketCommentsTime 'organization:Relationship:Organization:CASCADE; ticket:Relationship:Ticket:CASCADE; lastCommentAt:DateTimeUtc; lastResidentCommentAt:DateTimeUtc;'`
 */

const { historical, versioned, uuided, tracked, softDeleted, dvAndSender } = require('@open-condo/keystone/plugins')
const { GQLListSchema } = require('@open-condo/keystone/schema')

const { addOrganizationFieldPlugin } = require('@condo/domains/organization/schema/plugins/addOrganizationFieldPlugin')
const access = require('@condo/domains/ticket/access/TicketCommentsTime')

const TicketCommentsTime = new GQLListSchema('TicketCommentsTime', {
    schemaDoc: 'The time of the last comment and the last comment of the resident in a specific ticket',
    fields: {
        ticket: {
            schemaDoc: 'Link to the ticket',
            type: 'Relationship',
            ref: 'Ticket',
            isRequired: true,
            knexOptions: { isNotNullable: true },
            kmigratorOptions: { null: false, on_delete: 'models.CASCADE' },
        },

        lastCommentAt: {
            schemaDoc: 'Time of last comment with resident type in this ticket',
            type: 'DateTimeUtc',
            isRequired: true,
        },

        lastResidentCommentAt: {
            schemaDoc: 'Time of last comment with resident user in this ticket',
            type: 'DateTimeUtc',
        },
    },
    kmigratorOptions: {
        constraints: [
            {
                type: 'models.UniqueConstraint',
                fields: ['ticket'],
                condition: 'Q(deletedAt__isnull=True)',
                name: 'ticket_comments_time_unique_ticket',
            },
        ],
    },
    plugins: [
        addOrganizationFieldPlugin({ fromField: 'ticket', isRequired: true }),
        uuided(),
        versioned(),
        tracked(),
        softDeleted(),
        dvAndSender(),
        historical(),
    ],
    access: {
        read: access.canReadTicketCommentsTimes,
        create: access.canManageTicketCommentsTimes,
        update: access.canManageTicketCommentsTimes,
        delete: false,
        auth: true,
    },
})

module.exports = {
    TicketCommentsTime,
}
