const ALREADY_ACCEPTED_INVITATION = 'ALREADY_ACCEPTED_INVITATION'
const ALREADY_INVITED = 'ALREADY_INVITED'
const NAME_TOO_SHORT_ERROR = 'ORGANIZATION_NAME_IS_TOO_SHORT'
const NAME_VALUE_INVALID = 'ORGANIZATION_NAME_IS_INVALID'
const TIN_TOO_SHORT_ERROR = 'TIN_IS_TOO_SHORT'
const TIN_VALUE_INVALID = 'TIN_IS_INVALID'
const UNABLE_TO_REGISTER_USER = 'UNABLE_TO_REGISTER_USER'

module.exports = {
    ALREADY_ACCEPTED_INVITATION,
    ALREADY_INVITED,
    NAME_TOO_SHORT_ERROR,
    NAME_VALUE_INVALID,
    TIN_TOO_SHORT_ERROR,
    TIN_VALUE_INVALID,
    UNABLE_TO_REGISTER_USER,
}
