const ALREADY_ACCEPTED_INVITATION = 'ALREADY_ACCEPTED_INVITATION'
const ALREADY_INVITED = 'ALREADY_INVITED'
const EMPTY_NAME_ERROR = '[name.is.too.short'
const TIN_TOO_SHORT_ERROR = '[tin.is.too.short'
const TIN_VALUE_INVALID = '[tin.value.is.invalid'
const UNABLE_TO_REGISTER_USER = 'UNABLE_TO_REGISTER_USER'

module.exports = {
    ALREADY_ACCEPTED_INVITATION,
    ALREADY_INVITED,
    EMPTY_NAME_ERROR,
    TIN_TOO_SHORT_ERROR,
    TIN_VALUE_INVALID,
    UNABLE_TO_REGISTER_USER,
}
