const SERVICE_PROVIDER_PROFILE_FEATURE = 'SPP'
const ANALYTICS_V3 = 'ANALYTICS_V3'

const ALL_FEATURES = [
    SERVICE_PROVIDER_PROFILE_FEATURE,
    ANALYTICS_V3,
]

const ORGANIZATION_FEATURE_ENUM_NAME = 'OrganizationFeature'

module.exports = {
    SERVICE_PROVIDER_PROFILE_FEATURE,
    ANALYTICS_V3,
    ALL_FEATURES,
    ORGANIZATION_FEATURE_ENUM_NAME,
}
