const SERVICE_PROVIDER_PROFILE_FEATURE = 'SPP'
const ACTIVE_BANKING_FEATURE = 'active_banking'
const HIGH_REVENUE_CUSTOMER_FEATURE = 'high_revenue_customer'

const ALL_FEATURES = [
    SERVICE_PROVIDER_PROFILE_FEATURE,
    ACTIVE_BANKING_FEATURE,
    HIGH_REVENUE_CUSTOMER_FEATURE,
]

const ORGANIZATION_FEATURE_ENUM_NAME = 'OrganizationFeature'

module.exports = {
    SERVICE_PROVIDER_PROFILE_FEATURE,
    ACTIVE_BANKING_FEATURE,
    HIGH_REVENUE_CUSTOMER_FEATURE,
    ALL_FEATURES,
    ORGANIZATION_FEATURE_ENUM_NAME,
}
