const DEFAULT_REQUEST_LENGTH_LIMIT = 8 * 1024 // ~8k chars
const DEFAULT_VARIABLES_SIZE_LIMIT_IN_BYTES = 512 * 1024 // 512 KB
const ROOT_QUERY_LENGTH_EXCEEDED_ERROR_TYPE = 'ROOT_QUERY_LENGTH_EXCEEDED'
const VARIABLES_SIZE_EXCEEDED_ERROR_TYPE = 'VARIABLES_SIZE_EXCEEDED'


module.exports = {
    DEFAULT_REQUEST_LENGTH_LIMIT,
    DEFAULT_VARIABLES_SIZE_LIMIT_IN_BYTES,
    ROOT_QUERY_LENGTH_EXCEEDED_ERROR_TYPE,
    VARIABLES_SIZE_EXCEEDED_ERROR_TYPE,
}