const MAX_REQUESTS_IN_BATCH = 50
const MAX_MODIFY_OPERATIONS_IN_REQUEST = 10
const MAX_RETRIES_ON_NETWORK_ERROR = 5
const LOAD_CHUNK_SIZE = 50

module.exports = {
    MAX_REQUESTS_IN_BATCH,
    LOAD_CHUNK_SIZE,
    MAX_MODIFY_OPERATIONS_IN_REQUEST,
    MAX_RETRIES_ON_NETWORK_ERROR,
}