let unitId = 1

const buildingMapJson = {
    dv: 1,
    type: 'building',
    sections: [
        {
            id: 1,
            type: 'section',
            index: 1,
            name: 'Подъезд №1',
            floors: [
                {
                    id: 7,
                    type: 'floor',
                    index: 7,
                    name: '7',
                    units: [
                        { id: String(unitId++), type: 'unit' },
                        { id: String(unitId++), type: 'unit' },
                        { id: String(unitId++), type: 'unit' },
                        { id: String(unitId++), type: 'unit' },
                    ],
                },
                {
                    id: 6,
                    type: 'floor',
                    index: 6,
                    name: '6',
                    units: [
                        { id: String(unitId++), type: 'unit' },
                        { id: String(unitId++), type: 'unit' },
                        { id: String(unitId++), type: 'unit' },
                        { id: String(unitId++), type: 'unit' },
                    ],
                },
                {
                    id: 5,
                    type: 'floor',
                    index: 5,
                    name: '5',
                    units: [
                        { id: String(unitId++), type: 'unit' },
                        { id: String(unitId++), type: 'unit' },
                        { id: String(unitId++), type: 'unit' },
                        { id: String(unitId++), type: 'unit' },
                    ],
                },
                {
                    id: 4,
                    type: 'floor',
                    index: 4,
                    name: '4',
                    units: [
                        { id: String(unitId++), type: 'unit' },
                        { id: String(unitId++), type: 'unit' },
                        { id: String(unitId++), type: 'unit' },
                        { id: String(unitId++), type: 'unit' },
                    ],
                },
                {
                    id: 3,
                    type: 'floor',
                    index: 3,
                    name: '3',
                    units: [
                        { id: String(unitId++), type: 'unit' },
                        { id: String(unitId++), type: 'unit' },
                        { id: String(unitId++), type: 'unit' },
                        { id: String(unitId++), type: 'unit' },
                    ],
                },
                {
                    id: 2,
                    type: 'floor',
                    index: 2,
                    name: '2',
                    units: [
                        { id: String(unitId++), type: 'unit' },
                        { id: String(unitId++), type: 'unit' },
                        { id: String(unitId++), type: 'unit' },
                        { id: String(unitId++), type: 'unit' },
                    ],
                },
                {
                    id: 1,
                    type: 'floor',
                    index: 1,
                    name: '1',
                    units: [
                        { id: String(unitId++), type: 'unit', name: '1' },
                        { id: String(unitId++), type: 'unit' },
                        { id: String(unitId++), type: 'unit' },
                        { id: String(unitId++), type: 'unit' },
                    ],
                },
                // {
                //     id: -1,
                //     type: 'floor',
                //     index: -1,
                //     name: '-1',
                //     units: [{ id: unitId++, type: 'unit', name: 'S1' },
                //         { id: unitId++, type: 'unit', name: 'S2' },
                //         { id: unitId++, type: 'unit', name: 'S3' },
                //         { id: unitId++, type: 'unit', name: 'S4' }],
                // },
                // {
                //     id: -2,
                //     type: 'floor',
                //     index: -2,
                //     name: '-2',
                //     units: [{ id: unitId++, type: 'unit' }, { id: unitId++, type: 'unit' }, {
                //         id: unitId++,
                //         type: 'unit',
                //     }, { id: unitId++, type: 'unit' }],
                // },
                // {
                //     id: -3,
                //     type: 'floor',
                //     index: -3,
                //     name: '-3',
                //     units: [
                //         { id: unitId++, type: 'unit' },
                //         { id: unitId++, type: 'unit' },
                //         { id: unitId++, type: 'unit' }, { id: unitId++, type: 'unit' }],
                // },
                // {
                //     id: -4,
                //     type: 'floor',
                //     index: -4,
                //     name: '-4',
                //     units: [
                //         { id: unitId++, type: 'unit' }, { id: unitId++, type: 'unit' },
                //         { id: unitId++, type: 'unit' }, { id: unitId++, type: 'unit' }],
                // },
            ],
        },
        // {
        //     id: 2,
        //     type: 'section',
        //     name: 'P1/2',
        //     floors: [
        //         {
        //             id: 1,
        //             type: 'floor',
        //             index: 1,
        //             name: '1',
        //             units: [{ id: unitId++, type: 'unit', name: '22x' }, { id: unitId++, type: 'unit' }],
        //         },
        //
        //         {
        //             id: 2,
        //             type: 'floor',
        //             index: -1,
        //             name: '-1',
        //             units: [{ id: unitId++, type: 'unit', name: '11x' }, {
        //                 id: unitId++,
        //                 type: 'unit',
        //                 name: '12x',
        //             }],
        //         },
        //     ],
        // },
    ],
}

const buildingAddressMetaJson = {
    'postal_code': '115533',
    'country': 'Россия',
    'country_iso_code': 'RU',
    'region_fias_id': '0c5b2444-70a0-4932-980c-b4dc0d3f02b5',
    'region_kladr_id': '7700000000000',
    'region_iso_code': 'RU-MOW',
    'region_with_type': 'г Москва',
    'region_type': 'г',
    'region_type_full': 'город',
    'region': 'Москва',
    'city_fias_id': '0c5b2444-70a0-4932-980c-b4dc0d3f02b5',
    'city_kladr_id': '7700000000000',
    'city_with_type': 'г Москва',
    'city_type': 'г',
    'city_type_full': 'город',
    'city': 'Москва',
    'street_fias_id': 'fb4bcd3e-29ac-4a9e-809a-00378b5683f0',
    'street_kladr_id': '77000000000194300',
    'street_with_type': 'Нагатинская наб',
    'street_type': 'наб',
    'street_type_full': 'набережная',
    'street': 'Нагатинская',
    'house_fias_id': '9dd6056a-0b70-4451-8324-ca83d56c7266',
    'house_kladr_id': '7700000000019430123',
    'house_type': 'д',
    'house_type_full': 'дом',
    'house': '10',
    'block_type': 'к',
    'block_type_full': 'корпус',
    'block': '3',
    'fias_id': '9dd6056a-0b70-4451-8324-ca83d56c7266',
    'fias_code': '77000000000000019430123',
    'fias_level': '8',
    'fias_actuality_state': '0',
    'kladr_id': '7700000000019430123',
    'geoname_id': '524894',
    'capital_marker': '0',
    'okato': '45296571000',
    'oktmo': '45918000',
    'tax_office': '7725',
    'tax_office_legal': '7725',
    'geo_lat': '55.682935',
    'geo_lon': '37.64542',
    'qc_geo': '0',
    'address': 'г Москва, Нагатинская наб, д 10 к 3',
    'dv': 1,
}

module.exports = {
    buildingMapJson,
    buildingAddressMetaJson,
}
