const B2C_APP_BUILD_UNIQUE_VERSION_CONSTRAINT = 'b2c_app_build_unique_version_app'
const B2C_APP_PUBLISH_REQUEST_UNIQUE_CONSTRAINT = 'b2c_app_publish_request_unique_app'
const OIDC_CLIENT_UNIQUE_B2C_APP_CONSTRAINT = 'oidc_client_unique_b2c_app'

module.exports = {
    B2C_APP_BUILD_UNIQUE_VERSION_CONSTRAINT,
    B2C_APP_PUBLISH_REQUEST_UNIQUE_CONSTRAINT,
    OIDC_CLIENT_UNIQUE_B2C_APP_CONSTRAINT,
}