const INVALID_BUILD_VERSION = 'INVALID_BUILD_VERSION'
const FIRST_PUBLISH_WITHOUT_INFO = 'FIRST_PUBLISH_WITHOUT_INFO'
const APP_NOT_FOUND = 'APP_NOT_FOUND'
const CONDO_APP_NOT_FOUND = 'APP_NOT_FOUND'
const BUILD_NOT_FOUND = 'BUILD_NOT_FOUND'
const OIDC_CLIENT_NOT_FOUND = 'OIDC_CLIENT_NOT_FOUND'
const OIDC_CLIENT_NO_REDIRECT_URI = 'OIDC_CLIENT_NO_REDIRECT_URI'
const PUBLISH_NOT_ALLOWED = 'PUBLISH_NOT_ALLOWED'
const APPROVE_NOT_ALLOWED = 'APPROVE_NOT_ALLOWED'
const INVALID_GRANT_TYPES = 'INVALID_GRANT_TYPES'
const INVALID_RESPONSE_TYPES = 'INVALID_RESPONSE_TYPES'

module.exports = {
    INVALID_BUILD_VERSION,
    FIRST_PUBLISH_WITHOUT_INFO,
    APP_NOT_FOUND,
    CONDO_APP_NOT_FOUND,
    BUILD_NOT_FOUND,
    OIDC_CLIENT_NOT_FOUND,
    OIDC_CLIENT_NO_REDIRECT_URI,
    APPROVE_NOT_ALLOWED,
    PUBLISH_NOT_ALLOWED,
    INVALID_GRANT_TYPES,
    INVALID_RESPONSE_TYPES,
}