const INVALID_BUILD_VERSION = 'INVALID_BUILD_VERSION'
const FIRST_PUBLISH_WITHOUT_INFO = 'FIRST_PUBLISH_WITHOUT_INFO'
const APP_NOT_FOUND = 'APP_NOT_FOUND'
const CONDO_APP_NOT_FOUND = 'APP_NOT_FOUND'
const BUILD_NOT_FOUND = 'BUILD_NOT_FOUND'
const PUBLISH_NOT_ALLOWED = 'PUBLISH_NOT_ALLOWED'
const APPROVE_NOT_ALLOWED = 'APPROVE_NOT_ALLOWED'

module.exports = {
    INVALID_BUILD_VERSION,
    FIRST_PUBLISH_WITHOUT_INFO,
    APP_NOT_FOUND,
    CONDO_APP_NOT_FOUND,
    BUILD_NOT_FOUND,
    APPROVE_NOT_ALLOWED,
    PUBLISH_NOT_ALLOWED,
}