const INVALID_BUILD_VERSION = 'INVALID_BUILD_VERSION'
const FIRST_PUBLISH_WITHOUT_INFO = 'FIRST_PUBLISH_WITHOUT_INFO'
const APP_NOT_FOUND = 'APP_NOT_FOUND'

module.exports = {
    INVALID_BUILD_VERSION,
    FIRST_PUBLISH_WITHOUT_INFO,
    APP_NOT_FOUND,
}