const OIDC_SECRET_LENGTH = 32
const OIDC_SECRET_CHAR_PATTERN = /[a-zA-Z0-9]/

const OIDC_IMPLICIT_GRANT_TYPE = 'implicit'
const OIDC_AUTH_CODE_GRANT_TYPE = 'authorization_code'
const OIDC_REFRESH_TOKEN_GRANT_TYPE = 'refresh_token'
const OIDC_GRANT_TYPES = [
    OIDC_IMPLICIT_GRANT_TYPE,
    OIDC_AUTH_CODE_GRANT_TYPE,
    OIDC_REFRESH_TOKEN_GRANT_TYPE,
]

const OIDC_TOKEN_AUTH_BASIC_METHOD = 'client_secret_basic'
const OIDC_TOKEN_AUTH_POST_METHOD = 'client_secret_post'
const OIDC_TOKEN_AUTH_METHODS = [
    OIDC_TOKEN_AUTH_BASIC_METHOD,
    OIDC_TOKEN_AUTH_POST_METHOD,
]


module.exports = {
    OIDC_SECRET_LENGTH,
    OIDC_SECRET_CHAR_PATTERN,
    OIDC_GRANT_TYPES,
    OIDC_TOKEN_AUTH_BASIC_METHOD,
    OIDC_TOKEN_AUTH_METHODS,
}