const PROPERTY_WITH_SAME_ADDRESS_EXIST = '[unique:alreadyExists:address]'

const FLAT_WITHOUT_FLAT_TYPE = 'FLAT_WITHOUT_FLAT_TYPE'

const PROPERTY_ALREADY_EXISTS = 'PROPERTY_ALREADY_EXISTS'

module.exports = {
    PROPERTY_WITH_SAME_ADDRESS_EXIST,
    FLAT_WITHOUT_FLAT_TYPE,
    PROPERTY_ALREADY_EXISTS,
}
