const PROPERTY_TYPE_APARTMENT_BLOCK = 'apartment_block'
const PROPERTY_TYPE_CONDO = 'condo'
const PROPERTY_TYPE_HOUSE = 'house'
const PROPERTY_TYPE_HOSTEL = 'hostel'
const PROPERTY_TYPE_MIXED = 'mixed'

const PROPERTY_TYPES = [
    PROPERTY_TYPE_APARTMENT_BLOCK,
    PROPERTY_TYPE_CONDO,
    PROPERTY_TYPE_HOUSE,
    PROPERTY_TYPE_HOSTEL,
    PROPERTY_TYPE_MIXED,
]

const RENTAL_UNIT_TYPE_APARTMENT = 'apartment'
const RENTAL_UNIT_TYPE_HOUSE = 'house'
const RENTAL_UNIT_TYPE_FLOOR = 'floor'
const RENTAL_UNIT_TYPE_ROOM = 'room'
const RENTAL_UNIT_TYPE_BED = 'bed'

const RENTAL_UNIT_TYPES = [
    RENTAL_UNIT_TYPE_APARTMENT,
    RENTAL_UNIT_TYPE_HOUSE,
    RENTAL_UNIT_TYPE_FLOOR,
    RENTAL_UNIT_TYPE_ROOM,
    RENTAL_UNIT_TYPE_BED,
]

module.exports = {
    PROPERTY_TYPE_APARTMENT_BLOCK,
    PROPERTY_TYPE_CONDO,
    PROPERTY_TYPE_HOUSE,
    PROPERTY_TYPE_HOSTEL,
    PROPERTY_TYPE_MIXED,
    PROPERTY_TYPES,
    RENTAL_UNIT_TYPE_APARTMENT,
    RENTAL_UNIT_TYPE_HOUSE,
    RENTAL_UNIT_TYPE_FLOOR,
    RENTAL_UNIT_TYPE_ROOM,
    RENTAL_UNIT_TYPE_BED,
    RENTAL_UNIT_TYPES,
}
