/**
 * Generated by `createschema acquiring.MultiPayment 'amount:Decimal; commission?:Decimal; time:DateTimeUtc; cardNumber:Text; serviceCategory:Text;'`
 */

const { throwAuthenticationError } = require('@open-condo/keystone/apolloErrorFormatter')

const { checkAcquiringIntegrationAccessRights } = require(
    '@condo/domains/acquiring/utils/accessSchema')
const { RESIDENT, SERVICE } = require('@condo/domains/user/constants/common')


async function canReadMultiPayments ({ authentication: { item: user } }) {
    if (!user) return throwAuthenticationError()
    if (user.deletedAt) return false

    if (user.isSupport || user.isAdmin) return {}

    if (user.type === RESIDENT) {
        return {
            user: { id: user.id },
        }
    }

    // Acquiring integration account can get only MultiPayments linked to this integration
    return { integration: { accessRights_some: { user: { id: user.id } }, deletedAt: null } }
}

async function canManageMultiPayments ({ authentication: { item: user }, operation, itemId }) {
    if (!user) return throwAuthenticationError()
    if (user.deletedAt) return false

    if (user.isAdmin) return true
    // Can be created only through custom mutation or by admin, can be modified by acquiring integration account
    if (operation === 'create') return false
    // Acquiring integration account can update only it's own multipayment
    if (operation === 'update' && itemId) return { integration: { accessRights_some: { user: { id: user.id } } } }

    return false
}

async function canReadMultiPaymentsSensitiveData ({ authentication: { item: user }, existingItem }) {
    if (!user || user.deletedAt) return false
    if (user.isAdmin || user.isSupport) return true

    return !!(await checkAcquiringIntegrationAccessRights(user.id, [existingItem.integration]))
}

async function canReadPayerInfoField ({ authentication: { item: user }, existingItem }) {
    if (!user || user.deletedAt) return false
    if (user.isAdmin) return true
    if (user.type !== SERVICE) return false

    return !!(await checkAcquiringIntegrationAccessRights(user.id, [existingItem.integration]))
}
/*
  Rules are logical functions that used for list access, and may return a boolean (meaning
  all or no items are available) or a set of filters that limit the available items.
*/
module.exports = {
    canReadMultiPayments,
    canManageMultiPayments,
    canReadMultiPaymentsSensitiveData,
    canReadPayerInfoField,
}
