/**
 * Generated by `createschema acquiring.Payment 'amount:Decimal; currencyCode:Text; time:DateTimeUtc; accountNumber:Text; purpose?:Text; receipts:Relationship:BillingReceipt:PROTECT; multiPayment:Relationship:MultiPayment:PROTECT; context:Relationship:AcquiringIntegrationContext:PROTECT;' --force`
 */

const { RESIDENT } = require('@condo/domains/user/constants/common')
const { AcquiringIntegrationAccessRight } = require('@condo/domains/acquiring/utils/serverSchema')
const { throwAuthenticationError } = require('@condo/domains/common/utils/apolloErrorFormatter')

async function canReadPayments ({ authentication: { item: user } }) {
    if (!user) return throwAuthenticationError()
    if (user.deletedAt) return false
    if (user.isAdmin || user.isSupport) return {}
    // User can get only it's own payments
    if (user.type === RESIDENT) {
        return {
            multiPayment: { user: { id: user.id } },
        }
    }
    return {
        OR: [
            // Acquiring integration account can see it's payments
            { context: { integration: { accessRights_some: { user: { id: user.id } } } } },
            // Employee with `canManagePayments` can see theirs organization payments
            { context: { organization: { employees_some: { user: { id: user.id }, role: { canManagePayments: true }, deletedAt: null, isBlocked: false } } } },
        ],
    }
}

async function canManagePayments ({ authentication: { item: user }, operation, context }) {
    if (!user) return throwAuthenticationError()
    if (user.deletedAt) return false
    if (user.isAdmin) return true
    if (operation === 'create') {
        // Acquiring integration can create payments, linked to own context and own MultiPayments
        const rights = await AcquiringIntegrationAccessRight.count(context, {
            user: { id: user.id },
        })
        if (rights) return true
    } else if (operation === 'update') {
        // Cannot be updated, since it's strange to change payment details after...
        return false
    }
    return false
}

/*
  Rules are logical functions that used for list access, and may return a boolean (meaning
  all or no items are available) or a set of filters that limit the available items.
*/
module.exports = {
    canReadPayments,
    canManagePayments,
}
