const ERROR_MESSAGES = {
    VALIDATION_AUTH_DATA_KEYS_MISMATCH: 'VALIDATION_AUTH_DATA_KEYS_MISMATCH',
    VALIDATION_AUTH_DATA_EXPIRED: 'VALIDATION_AUTH_DATA_EXPIRED',
    VALIDATION_AUTH_DATA_SIGN_INVALID: 'VALIDATION_AUTH_DATA_SIGN_INVALID',

    NOT_SUPPORTED_USER_TYPE: 'NOT_SUPPORTED_USER_TYPE',
    BODY_MISSING: 'BODY_MISSING',
    INVALID_REDIRECT_URL: 'INVALID_REDIRECT_URL',
    SUPER_USERS_NOT_ALLOWED: 'SUPER_USERS_NOT_ALLOWED',

    USER_IS_NOT_REGISTERED: 'USER_IS_NOT_REGISTERED',
}

module.exports = {
    ERROR_MESSAGES,
}