const DEFAULT_MUTATION_WEIGHT = 5
const DEFAULT_QUERY_WEIGHT = 1
const DEFAULT_MAX_TOTAL_RESULTS = 1000
const DEFAULT_AUTHED_QUOTA = 5000
const DEFAULT_NON_AUTHED_QUOTA = 100
const DEFAULT_QUOTA_WINDOW = '1h'
const DEFAULT_WHERE_COMPLEXITY_FACTOR = 2


module.exports = {
    DEFAULT_QUERY_WEIGHT,
    DEFAULT_MUTATION_WEIGHT,
    DEFAULT_MAX_TOTAL_RESULTS,
    DEFAULT_AUTHED_QUOTA,
    DEFAULT_NON_AUTHED_QUOTA,
    DEFAULT_QUOTA_WINDOW,
    DEFAULT_WHERE_COMPLEXITY_FACTOR,
}