const TELEGRAM_AUTH_STATUS_PENDING = 'pending'
const TELEGRAM_AUTH_STATUS_SUCCESS = 'success'
const TELEGRAM_AUTH_STATUS_ERROR = 'error'

const TELEGRAM_AUTH_REDIS_STATE_PREFIX = 'telegram:state:'
const TELEGRAM_AUTH_REDIS_STATUS_PREFIX = 'telegram:status:'
const TELEGRAM_AUTH_REDIS_TOKEN_PREFIX = 'telegram:token:'

const TELEGRAM_AUTH_REDIS_TTL = 300 // 5 mins

module.exports = {
    TELEGRAM_AUTH_STATUS_PENDING,
    TELEGRAM_AUTH_STATUS_SUCCESS,
    TELEGRAM_AUTH_STATUS_ERROR,
    TELEGRAM_AUTH_REDIS_STATE_PREFIX,
    TELEGRAM_AUTH_REDIS_STATUS_PREFIX,
    TELEGRAM_AUTH_REDIS_TOKEN_PREFIX,
    TELEGRAM_AUTH_REDIS_TTL,
}