const MAX_DESCRIPTION_DISPLAY_LENGTH = 150
const MIN_DESCRIPTION_LENGTH = 6
const MAX_FILTERED_ELEMENTS = 20
const MAX_TAG_TEXT_LENGTH = 30
const MAX_PHONE_LENGTH = 15
const MIN_PHONE_LENGTH = 11

export {
    MAX_DESCRIPTION_DISPLAY_LENGTH,
    MIN_DESCRIPTION_LENGTH,
    MAX_FILTERED_ELEMENTS,
    MAX_TAG_TEXT_LENGTH,
    MAX_PHONE_LENGTH,
    MIN_PHONE_LENGTH,
}
