const B2B_APP_ACCESS_RIGHT_SET_PENDING_STATUS = 'pending'
const B2B_APP_ACCESS_RIGHT_SET_APPROVED_STATUS = 'approved'
const B2B_APP_ACCESS_RIGHT_SET_STATUS_OPTIONS = [
    B2B_APP_ACCESS_RIGHT_SET_PENDING_STATUS,
    B2B_APP_ACCESS_RIGHT_SET_APPROVED_STATUS,
]

module.exports = {
    B2B_APP_ACCESS_RIGHT_SET_PENDING_STATUS,
    B2B_APP_ACCESS_RIGHT_SET_APPROVED_STATUS,
    B2B_APP_ACCESS_RIGHT_SET_STATUS_OPTIONS,
}