const B2B_APP_PUBLISH_REQUEST_UNIQUE_CONSTRAINT = 'b2b_app_publish_request_unique_app'

const B2C_APP_BUILD_UNIQUE_VERSION_CONSTRAINT = 'b2c_app_build_unique_version_app'
const B2C_APP_PUBLISH_REQUEST_UNIQUE_CONSTRAINT = 'b2c_app_publish_request_unique_app'
const B2C_APP_ACCESS_RIGHT_UNIQUE_APP_CONSTRAINT = 'b2c_app_access_right_unique_app'

module.exports = {
    B2B_APP_PUBLISH_REQUEST_UNIQUE_CONSTRAINT,

    B2C_APP_BUILD_UNIQUE_VERSION_CONSTRAINT,
    B2C_APP_PUBLISH_REQUEST_UNIQUE_CONSTRAINT,
    B2C_APP_ACCESS_RIGHT_UNIQUE_APP_CONSTRAINT,
}