/**
 * Generated by `createschema subscription.ServiceSubscription 'type:Select:default,sbbol; isTrial:Checkbox; organization:Relationship:Organization:CASCADE; startAt:DateTimeUtc; finishAt:DateTimeUtc;'`
 * In most cases you should not change it by hands
 * Please, don't remove `AUTOGENERATE MARKER`s
 */
const { faker } = require('@faker-js/faker')

const { generateGQLTestUtils, throwIfError } = require('@open-condo/codegen/generate.test.utils')

const { MANAGING_COMPANY_TYPE } = require('@condo/domains/organization/constants/common')
const {
    SubscriptionPlan: SubscriptionPlanGQL,
    SubscriptionPlanPricingRule: SubscriptionPlanPricingRuleGQL,
    SubscriptionContext: SubscriptionContextGQL,
    ACTIVATE_SUBSCRIPTION_PLAN_MUTATION,
    GET_AVAILABLE_SUBSCRIPTION_PLANS_QUERY,
} = require('@condo/domains/subscription/gql')
/* AUTOGENERATE MARKER <IMPORT> */

const SubscriptionPlan = generateGQLTestUtils(SubscriptionPlanGQL)
const SubscriptionPlanPricingRule = generateGQLTestUtils(SubscriptionPlanPricingRuleGQL)
const SubscriptionContext = generateGQLTestUtils(SubscriptionContextGQL)
/* AUTOGENERATE MARKER <CONST> */

async function createTestSubscriptionPlan (client, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        name: faker.lorem.word(),
        organizationType: MANAGING_COMPANY_TYPE,
        dv: 1,
        sender,
        ...extraAttrs,
    }
    const obj = await SubscriptionPlan.create(client, attrs)
    return [obj, attrs]
}

async function updateTestSubscriptionPlan (client, id, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    if (!id) throw new Error('no id')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        ...extraAttrs,
    }
    const obj = await SubscriptionPlan.update(client, id, attrs)
    return [obj, attrs]
}

async function createTestSubscriptionPlanPricingRule (client, subscriptionPlan, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    if (!subscriptionPlan || !subscriptionPlan.id) throw new Error('no subscriptionPlan.id')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        name: faker.commerce.productName(),
        subscriptionPlan: { connect: { id: subscriptionPlan.id } },
        period: 'month',
        price: '1000.00',
        currencyCode: 'RUB',
        ...extraAttrs,
    }
    const obj = await SubscriptionPlanPricingRule.create(client, attrs)
    return [obj, attrs]
}

async function updateTestSubscriptionPlanPricingRule (client, id, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    if (!id) throw new Error('no id')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        ...extraAttrs,
    }
    const obj = await SubscriptionPlanPricingRule.update(client, id, attrs)
    return [obj, attrs]
}

async function createTestSubscriptionContext (client, organization, subscriptionPlan, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    if (!organization || !organization.id) throw new Error('no organization.id')
    if (!subscriptionPlan || !subscriptionPlan.id) throw new Error('no subscriptionPlan.id')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        organization: { connect: { id: organization.id } },
        subscriptionPlan: { connect: { id: subscriptionPlan.id } },
        ...extraAttrs,
    }
    const obj = await SubscriptionContext.create(client, attrs)
    return [obj, attrs]
}

async function updateTestSubscriptionContext (client, id, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    if (!id) throw new Error('no id')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        ...extraAttrs,
    }
    const obj = await SubscriptionContext.update(client, id, attrs)
    return [obj, attrs]
}


async function activateSubscriptionPlanByTestClient (client, organization, pricingRule, extraAttrs = {}) {
    if (!client) throw new Error('no client')
    if (!organization || !organization.id) throw new Error('no organization.id')
    if (!pricingRule || !pricingRule.id) throw new Error('no pricingRule.id')
    const sender = { dv: 1, fingerprint: faker.random.alphaNumeric(8) }

    const attrs = {
        dv: 1,
        sender,
        organization: { id: organization.id },
        pricingRule: { id: pricingRule.id },
        ...extraAttrs,
    }
    const { data, errors } = await client.mutate(ACTIVATE_SUBSCRIPTION_PLAN_MUTATION, { data: attrs })
    throwIfError(data, errors)
    return [data.result, attrs]
}

async function getAvailableSubscriptionPlansByTestClient (client, organization) {
    if (!client) throw new Error('no client')
    if (!organization || !organization.id) throw new Error('no organization.id')

    const { data, errors } = await client.query(GET_AVAILABLE_SUBSCRIPTION_PLANS_QUERY, { organization: { id: organization.id } })
    throwIfError(data, errors, { query: GET_AVAILABLE_SUBSCRIPTION_PLANS_QUERY, variables: { organization: { id: organization.id } } })
    return [data.result, {}]
}
/* AUTOGENERATE MARKER <FACTORY> */

module.exports = {
    SubscriptionPlan, createTestSubscriptionPlan, updateTestSubscriptionPlan,
    SubscriptionPlanPricingRule, createTestSubscriptionPlanPricingRule, updateTestSubscriptionPlanPricingRule,
    SubscriptionContext, createTestSubscriptionContext, updateTestSubscriptionContext,
    activateSubscriptionPlanByTestClient,
    getAvailableSubscriptionPlansByTestClient,
/* AUTOGENERATE MARKER <EXPORTS> */
}
