const {
    FILE_RECORD_META_FIELDS,
    FILE_RECORD_PUBLIC_META_FIELDS,
    FILE_RECORD_USER_META,
    FILE_RECORD_ATTACHMENTS,
    FileRecordScalarSchema,
} = require('./FileRecord')

module.exports = {
    FILE_RECORD_META_FIELDS,
    FILE_RECORD_PUBLIC_META_FIELDS,
    FileRecordScalarSchema,
    FILE_RECORD_USER_META,
    FILE_RECORD_ATTACHMENTS,
}
