/**
 * Generated by `createschema ticket.TicketPropertyHintProperty 'organization:Relationship:Organization:CASCADE;ticketPropertyHint:Relationship:TicketPropertyHint:CASCADE; property:Relationship:Property:SET_NULL;'`
 */

import {
    TicketPropertyHintProperty,
    TicketPropertyHintPropertyCreateInput,
    TicketPropertyHintPropertyUpdateInput,
    QueryAllTicketPropertyHintPropertiesArgs, 
} from '@app/condo/schema'

import { generateReactHooks } from '@open-condo/codegen/generate.hooks'

import { TicketPropertyHintProperty as TicketPropertyHintPropertyGQL } from '@condo/domains/ticket/gql'

const {
    useObject,
    useObjects,
    useAllObjects,
    useCreate,
    useUpdate,
    useSoftDelete,
} = generateReactHooks<TicketPropertyHintProperty, TicketPropertyHintPropertyCreateInput, TicketPropertyHintPropertyUpdateInput, QueryAllTicketPropertyHintPropertiesArgs>(TicketPropertyHintPropertyGQL)

export {
    useObject,
    useObjects,
    useAllObjects,
    useCreate,
    useUpdate,
    useSoftDelete,
}
