// TODO(@savelevmatthew): Think about exporting constants later
const ACCESS_DENIED_ERROR = 'ACCESS_DENIED'
const UNKNOWN_ERROR = 'UNKNOWN_ERROR'
const UNKNOWN_METHOD_ERROR = 'UNKNOWN_METHOD'
const INVALID_PARAMETERS_ERROR = 'INVALID_PARAMETERS'
const HANDLER_ERROR = 'HANDLER_ERROR'
const TIMEOUT_REACHED_ERROR = 'TIMEOUT_REACHED'

const ACCESS_DENIED_ERROR_CODE = 0
const UNKNOWN_ERROR_CODE = 1
const UNKNOWN_METHOD_ERROR_CODE = 2
const INVALID_PARAMETERS_ERROR_CODE = 3
const HANDLER_ERROR_CODE = 4
const TIMEOUT_REACHED_ERROR_CODE = 5

const ERROR_CODES = {
    [ACCESS_DENIED_ERROR]: ACCESS_DENIED_ERROR_CODE,
    [UNKNOWN_ERROR]: UNKNOWN_ERROR_CODE,
    [UNKNOWN_METHOD_ERROR]: UNKNOWN_METHOD_ERROR_CODE,
    [INVALID_PARAMETERS_ERROR]: INVALID_PARAMETERS_ERROR_CODE,
    [HANDLER_ERROR]: HANDLER_ERROR_CODE,
    [TIMEOUT_REACHED_ERROR]: TIMEOUT_REACHED_ERROR_CODE,
} as const

export type ErrorReason = keyof typeof ERROR_CODES

export type ErrorCode<Reason extends ErrorReason> = typeof ERROR_CODES[Reason]
