const INVALID_PHONE = 'INVALID_PHONE'
const USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS'
const ACTION_NOT_FOUND = 'ACTION_NOT_FOUND'
const PASSWORD_TOO_SIMPLE = 'PASSWORD_TOO_SIMPLE'

module.exports = {
    INVALID_PHONE,
    USER_ALREADY_EXISTS,
    ACTION_NOT_FOUND,
    PASSWORD_TOO_SIMPLE,
}