const MIN_PASSWORD_LENGTH = 12
const MIN_PASSWORD_DIFFERENT_CHARACTERS = 4
const CONFIRM_ACTION_CODE_LENGTH = 4
const CONFIRM_ACTION_TTL_IN_SEC = 5 * 60 // 5 min
const CONFIRM_ACTION_DAILY_LIMIT_BY_IP = 20
const CONFIRM_ACTION_DAILY_LIMIT_BY_PHONE = 10
const CONFIRM_ACTION_MAX_ATTEMPTS = 5

module.exports = {
    MIN_PASSWORD_LENGTH,
    MIN_PASSWORD_DIFFERENT_CHARACTERS,
    CONFIRM_ACTION_CODE_LENGTH,
    CONFIRM_ACTION_TTL_IN_SEC,
    CONFIRM_ACTION_DAILY_LIMIT_BY_IP,
    CONFIRM_ACTION_DAILY_LIMIT_BY_PHONE,
    CONFIRM_ACTION_MAX_ATTEMPTS,
}
