const MIN_PASSWORD_LENGTH = 12
const MIN_PASSWORD_DIFFERENT_CHARACTERS = 4
const CONFIRM_ACTION_CODE_LENGTH = 4
const CONFIRM_ACTION_TTL_IN_SEC = 5 * 60 // 5 min

module.exports = {
    MIN_PASSWORD_LENGTH,
    MIN_PASSWORD_DIFFERENT_CHARACTERS,
    CONFIRM_ACTION_CODE_LENGTH,
    CONFIRM_ACTION_TTL_IN_SEC,
}
