on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          ssh-key: ${{ secrets.SSH_DOCK_SERVER_PRIVATE_KEY }}
          ref: ${{ inputs.ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install packages
        run: |
          npm i -g turbo
          yarn install --immutable
          pip3 install django
          pip3 install psycopg2-binary

      - name: Docker compose up databases
        run: |
          docker compose up -d postgresdb postgresdb-replica redis

      - name: Build deps
        run: yarn workspace @app/condo build:deps

      - name: Prepare condo app
        run: node bin/prepare.js -f condo

      - name: Build condo app
        run: yarn workspace @app/condo build

      - name: Start server in production mode
        run: |
          set -x
          export NOTIFICATION__SEND_ALL_MESSAGES_TO_CONSOLE=true
          export NOTIFICATION__DISABLE_LOGGING=true
          export WORKER_CONCURRENCY=50
          export APOLLO_BATCHING_ENABLED=true

          echo 'JEST_MOCKS_ENABLED=true' >> .env
          echo 'DISABLE_CAPTCHA=true' >> .env
  
          yarn workspace @app/condo start &
          node bin/wait-apps-apis.js -f condo

      - name: Run cypress tests
        run: |
          yarn workspace @app/condo cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }} -b chrome -C ./cypress/cypress.config.ts

          kill $(jobs -p) || echo 'background worker and dev server is already killed!'
          killall node || echo 'no node processes'

        env:
          NODE_ENV: development
          DISABLE_LOGGING: true

      - name: Upload screenshots artifact
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: |
            ./apps/condo/cypress/screenshots
          retention-days: 2
