name: Cleanup container registry
on:
  schedule:
    - cron:  '0 2 * * *'
  repository_dispatch:
    types: [cleanup]

jobs:
  cleanup:
    name: Cleanup
    runs-on: self-hosted
    env:
      WERF_SECRET_KEY: ${{ secrets.WERF_SECRET_KEY }}
      PULL_USER: ${{ secrets.PULL_USER }}
      PULL_PERSONAL_ACCESS_KEY: ${{ secrets.PULL_PERSONAL_ACCESS_KEY }}
      WERF_PARALLEL: 0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
          ssh-key: ${{ secrets.RUNNER_SSH_PRIVATE_KEY }}
      - name: Fetch all history for all tags and branches
        run: |
          if $(git rev-parse --is-shallow-repository)
          then
            git fetch --prune --unshallow
          else
            git fetch --prune
          fi
      - name: Cleanup
        uses: werf/actions/cleanup@v1.2
        with:
          kube-config-base64-data: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}
