name: Cleanup container registry
on:
  workflow_dispatch:
    branches:
      - '*'
  schedule:
    - cron:  '0 2 * * *'
  repository_dispatch:
    types: [cleanup]

jobs:
  cleanup:
    name: Cleanup
    runs-on: self-hosted
    env:
      WERF_SECRET_KEY: ${{ secrets.WERF_SECRET_KEY }}
      WERF_PARALLEL: 0
    steps:
      - name: Login to Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9  # v3.7.0
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.SBERCLOUD_CR_USERNAME }}
          password: ${{ secrets.SBERCLOUD_CR_PASSWORD }}
      - name: Install SSH key
        uses: shimataro/ssh-key-action@87a8f067114a8ce263df83e9ed5c849953548bc3  # v2.8.1
        with:
          key: ${{ secrets.SSH_DOCK_SERVER_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.SSH_DOCK_SERVER_KNOWN_HOSTS }}
          if_key_exists: replace
      - name: Set env for branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF##*/} | sed 's/\_/-/g')" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4.4.0
        with:
          fetch-depth: 0
          submodules: recursive
          ssh-key: ${{ secrets.SSH_DOCK_SERVER_PRIVATE_KEY }}
      - name: Fetch all history for all tags and branches
        run: |
          if $(git rev-parse --is-shallow-repository)
          then
            git fetch --prune --unshallow
          else
            git fetch --prune
          fi
      - name: Cleanup
        uses: werf/actions/cleanup@72a1f765ae1dca7762810df28d40c17b236cde60  # v1.2
        with:
          kube-config-base64-data: ${{ secrets.KUBECONFIG_BASE64_PROD_BACKUP_CLUSTER }}
        env:
          WERF_REPO: ${{ secrets.DOCKER_REGISTRY }}/condo/condo
          WERF_REPO_CONTAINER_REGISTRY: default
