name: "[development] Deploy"

concurrency: deploy_develop.yaml

on:
  workflow_dispatch:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  converge:
    name: "[development] Deploy"
    runs-on: self-hosted
    env:
      WERF_SECRET_KEY: ${{ secrets.WERF_SECRET_KEY }}
      PULL_USER: ${{ secrets.PULL_USER }}
      PULL_PERSONAL_ACCESS_KEY: ${{ secrets.PULL_PERSONAL_ACCESS_KEY }}
    steps:
      - name: Login to Sbercloud Container Registry
        uses: docker/login-action@v1
        with:
          registry: swr.ru-moscow-1.hc.sbercloud.ru
          username: ${{ secrets.SBERCLOUD_CR_USERNAME }}
          password: ${{ secrets.SBERCLOUD_CR_PASSWORD }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
          ssh-key: ${{ secrets.SSH_DOCK_SERVER_PRIVATE_KEY }}
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_DOCK_SERVER_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.SSH_DOCK_SERVER_KNOWN_HOSTS }}
          if_key_exists: replace          
      - name: Set env for branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF##*/} | sed 's/\_/-/g')" >> $GITHUB_ENV
      - name: Converge
        uses: werf/actions/converge@v1.2
        with:
          channel: beta
          env: development
          kube-config-base64-data: ${{ secrets.KUBECONFIG_BASE64_DEVELOPMENT_CLUSTER }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          WERF_SET_CI_CONDO_URL: "global.ci_condo_url=condo.d.doma.ai"
          WERF_SET_CI_CALLCENTER_URL: "global.ci_callcenter_url=callcenter.d.doma.ai"
          WERF_SET_CI_EPS_URL: "global.ci_eps_url=eps.d.doma.ai"
          WERF_SET_CI_RB_URL: "global.ci_rb_url=rb.d.doma.ai"
          WERF_SET_CI_INSURANCE_URL: "global.ci_insurance_url=insurance.d.doma.ai"
          WERF_SET_CI_REGISTRY_MA_URL: "global.ci_registry_ma_url=registry.d.doma.ai"
          WERF_SET_CI_MINIAPP_URL: "global.ci_miniapp_url=miniapp.d.doma.ai"
          WERF_SET_CI_PROPERTY_IMPORTER_URL: "global.ci_property_importer_url=property-importer.d.doma.ai"
          WERF_SET_CI_CLASSIFIER_URL: "global.ci_classifier_url=ml.d.doma.ai"
          WERF_SET_CI_ADDRESS_SERVICE_URL: "global.ci_address_service_url=address-service.d.doma.ai"
          WERF_SET_CI_TELEPHONY_URL: "global.ci_telephony_url=telephony.d.doma.ai"
          WERF_SET_CI_DEVPORTAL_URL: "global.ci_devportal_url=developers.d.doma.ai"
          WERF_SET_CI_PASSAPP_URL: "global.ci_passapp_url=passapp.d.doma.ai"
          WERF_NAMESPACE: "development"
          WERF_VIRTUAL_MERGE_FROM_COMMIT: "true"
          WERF_SET_CI_REF: "ci.werf.io/ref=${GITHUB_REF_NAME}"
          WERF_REPO: swr.ru-moscow-1.hc.sbercloud.ru/condo/condo
          WERF_REPO_CONTAINER_REGISTRY: default
