name: DEPLOY BRANCH

on:
  push:
    tags:
      - 'deploy/*/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_DOCK_SERVER_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.SSH_DOCK_SERVER_KNOWN_HOSTS }}
      - name: Prepare
        run: |
          cp .env.example .env
          sudo apt install -y pv
          ssh root@dev.doma.ai 'id'
      - name: Docker build and upload
        run: |
          TAG=$(git tag --points-at HEAD)
          SUBDOMAIN="$(cut -d'/' -f2 <<<$TAG | tr A-Z a-z | sed 's/[^a-z0-9]/-/g' | sed 's/^-+\|-+$//g')"
          VERSION="$(cut -d'/' -f3 <<<$TAG | tr A-Z a-z | sed 's/[^a-z0-9]/-/g' | sed 's/^-+\|-+$//g')"
          if [[ -z "$SUBDOMAIN" || -z "$VERSION" ]]; then
            exit 1
          fi

          echo "Deploy $SUBDOMAIN.dev.doma.ai version=$VERSION"
          set -x

          # build
          bash ./bin/warm-docker-cache
          DOCKER_COMPOSE_APP_IMAGE_TAG="$SUBDOMAIN" docker-compose build

          # remove prev images
          ssh root@dev.doma.ai "docker rmi apps:$SUBDOMAIN" || echo "no image"
          ssh root@dev.doma.ai "docker images -f "reference=dokku/$SUBDOMAIN" -q | xargs docker rmi" || echo "no useless images"

          # upload new image
          docker save apps:$SUBDOMAIN | bzip2 | pv | ssh root@dev.doma.ai 'bunzip2 | docker load'

          # deploy by image
          bash ./.github/workflows/deploy.dev.sh root@dev.doma.ai $SUBDOMAIN $VERSION by apps:$SUBDOMAIN
