# Opens PR (if not opened yet) on force-push caused by packages.ui.rebase.tokens.yml workflow
name: Open PR from "figma/promotion" branch

on:
  push:
    branches:
      - 'figma/promotion'

jobs:
  openPR:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4.4.0
        with:
          fetch-depth: 0
          submodules: recursive
          ssh-key: ${{ secrets.SSH_DOCK_SERVER_PRIVATE_KEY }}
          ref: main

      - name: Reset promotion branch
        run: |
          git fetch origin figma/promotion:figma/promotion
          git reset --hard figma/promotion

      - name: Create pull request
        uses: peter-evans/create-pull-request@38e0b6e68b4c852a5500a94740f0e535e0d7ba54  # v4.2.4
        id: cpr
        with:
          token: ${{ secrets.DESIGN_BOT_PAT }}
          branch: figma/promotion
          labels: 🤖 Automatic PR, 🎨 UI-kit, 👨🏻‍🎨 Request UI-kit review, ✋🙂 Review please, 📦 Packages
          title: '[UI-kit] Update figma tokens'
          assignees: SavelevMatthew
          reviewers: SavelevMatthew

      - name: Print PR outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
