name: Chromatic sync baseline

on:
  push:
    branches:
      - main
    paths:
      - 'packages/ui/src/**'

jobs:
  chromatic:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4.4.0
        with:
          fetch-depth: 0
          submodules: recursive
          ssh-key: ${{ secrets.SSH_DOCK_SERVER_PRIVATE_KEY }}

      - name: Install packages
        run: |
          npm i -g turbo
          yarn install --immutable

      - name: Publish chromatic build
        uses: chromaui/action@c93e0bc3a63aa176e14a75b61a31847cbfdd341c  # v1
        with:
          workingDir: packages/ui
          projectToken: ${{ secrets.UI_CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: "build:chromatic"
          # Auto-accepting build as a baseline
          autoAcceptChanges: true
