name: Lint design tokens

on:
  pull_request:
    paths:
      - 'packages/ui/src/tokens/**/*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
          ssh-key: ${{ secrets.SSH_DOCK_SERVER_PRIVATE_KEY }}

      - name: Install packages
        run: yarn install --immutable

      - name: Lint tokens refs
        run: yarn workspace @condo/ui build:tokens

      - name: Lint CSS variables
        run: yarn stylelint "packages/ui/src/tokens/**/*.css"