name: Test workflow

on:
  push:
    branches:
      - main

  # NOTE: change pull_request_target to pull_request if you want to change the CI in your branch
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  DOCKER_IMAGE: condo/condo-image:${{ github.event.pull_request.head.sha || github.sha }}
  DOCKER_IMAGE_FULL: ${{ secrets.DOCKER_REGISTRY }}/condo/condo-image:${{ github.event.pull_request.head.sha || github.sha }}
  PG_IMAGE_FULL: ${{ secrets.DOCKER_REGISTRY }}/doma/utils/postgres:16.4
  REDIS_IMAGE_FULL: ${{ secrets.DOCKER_REGISTRY }}/doma/utils/redis:6.2
  REF: ${{ github.event.pull_request.head.sha || github.ref }}

jobs:
  test-job:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code without submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'false'
          ssh-key: ${{ secrets.SSH_DOCK_SERVER_PRIVATE_KEY }}
          ref: ${{ env.REF }}
      - name: Prepare Node environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
      - run: node bin/collect-failed-tests.js
        env:
          PROMETHEUS_RW_SERVER_URL: ${{ secrets.K6_PROMETHEUS_RW_SERVER_URL }}
          PROMETHEUS_USER: ${{ secrets.K6_PROMETHEUS_USER }}
          PROMETHEUS_PASSWORD: ${{ secrets.K6_PROMETHEUS_PASSWORD }}

