name: Test CI Run

on:
  push:
    branches:
      - chore/os-ci
  workflow_dispatch:

env:
  REF: ${{ github.event.pull_request.head.sha || github.ref }}

jobs:
  open-source-build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest]
        node-version: [16.x]
    runs-on: ${{ matrix.os }}

    services:
      postgres:
        image: postgres:16.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: main
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:6.2
        ports:
          - 6379:6379

    steps:
      - name: Checkout code without submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'false'
          ssh-key: ${{ secrets.SSH_DOCK_SERVER_PRIVATE_KEY }}
          ref: ${{ env.REF }}

      - name: Debug Docker Info
        run: |
          docker version
          docker info

      - name: Prepare Node environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install packages
        run: |
          npm i -g turbo
          yarn --no-immutable

      - name: Build condo dependencies
        run: yarn workspace @app/condo build:deps

      - name: Prepare condo app
        run: node bin/prepare.js -f condo

      - name: Build condo app
        run: yarn workspace @app/condo build

      - name: Start condo app
        run: yarn workspace @app/condo build & node bin/wait-apps-apis.js -f condo
