name: Test CI Run

on:
  push:
    branches:
      - chore/os-ci
  workflow_dispatch:

env:
  REF: ${{ github.event.pull_request.head.sha || github.ref }}

jobs:
  open-source-build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest]
        node-version: [16.x]
        python-version: [3.13]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code without submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'false'
          ssh-key: ${{ secrets.SSH_DOCK_SERVER_PRIVATE_KEY }}
          ref: ${{ env.REF }}

      - name: Setup native Postgres (Windows Runner only)
        if: matrix.os == 'windows-latest'
        uses: ikalnytskyi/action-setup-postgres@v7
        with:
          postgres-version: 16

      - name: Setup native Redis (Windows Runner only)
        if: matrix.os == 'windows-latest'
        run: |
          choco install redis --version 6.2.17 -y
          redis-server --daemonize yes

      - name: Setup databases (Linux Runners)
        if: matrix.os != 'windows-latest'
        run: docker compose up -d postgresdb redis

      - name: Prepare Python environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Prepare Node environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install packages
        run: |
          pip install Django psycopg2-binary
          npm i -g turbo
          yarn --no-immutable

      - name: Build condo dependencies
        run: yarn workspace @app/condo build:deps

      - name: Prepare condo environment
        run: node bin/prepare.js -f condo

      - name: Build condo itself
        run: yarn workspace @app/condo build
